### ISSUE TITLE
Azure Firewall - Availability Zones

### ISSUE THREAD

**Issue by aj-msft** [Azure/terraform-azurerm-caf-enterprise-scale#447] opened 2022-08-29 06:14 UTC
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: v1.2.6 </p>
<p><strong>azure provider</strong>: 2.97.0 </p>
<p><strong>module</strong>: 2.3.0 </p>
<h3 id=description>Description </h3>
<p>When deploying Connectivity resources by disabling one of the zones under firewall, it configures the firewall, firewall policy and public IP address as expected. The issue I face is that the public IP is deployed in all Availability Zones and firewall is deployed in specified availability zones, so when I run a terraform plan the next time, it throws an error stating that changes were made to the public IP and the resource must be replaced. Since the public IP cannot be deleted from the firewall, terraform apply fails with the below error. </p>
<p># module.enterprise<em>scale.azurerm</em>public<em>ip.connectivity[&quot;/subscription/xxxxxx/publicIPAddresses/firewall-pip&quot;] must be replaced
 -/+ resource &quot;azurerm</em>public<em>ip&quot; &quot;connectivity&quot; {
     + fqdn               = (known after apply)
     ~ id                    = &quot;/subscription/xxxxxx/publicIPAddresses/firewall-pip&quot; -&gt; (known after apply)
     ~ ip</em>address      = &quot;20.190.x.x&quot; -&gt; (known after apply)
     -  ip_tags            = {} -&gt; null
               # (2 unchanged elements hidden)
           ]
           # (7 unchanged attributes hidden)
     }
Plan: 1 to add, 0 to change, 1 to destroy </p>
<h4 id=stepstoreproduce>Steps to Reproduce </h4>
<p>Enable Azure firewall: </p>
<ol>
<li>In settings.connectivity.tf change the azure_firewall block to true and set one of the zones to false. </li>
</ol>
<p>Eg: azure<em>firewall = {
              enabled = true
              config = {
                address</em>prefix                = &quot;10.10.0.0/24&quot;
                enable<em>dns</em>proxy              = true
                dns<em>servers                   = []
                base</em>policy<em>id                = &quot;&quot;
                private</em>ip<em>ranges             = []
                sku</em>tier                      = &quot;&quot;
                threat<em>intelligence</em>allowlist = []
                threat<em>intelligence</em>mode      = &quot;&quot; </p>
<pre><code>            availability_zones = {
              zone_1 = true
              zone_2 = true
              zone_3 = false
            }
          }
</code></pre>
<ol start=3>
<li>Run Terraform plan and the output would say 
Plan: 3 to add, 0 to change, 0 to destroy </li>
<li>Run terraform apply and once resources are deployed, verify through the portal
 Azure Firewall - Availability Zones: 1,2
 Public IP address - Availability Zones: 1,2,3 </li>
<li>Without making any other changes run Terraform plan again and the error would be thrown. </li>
</ol>
<h4 id=screenshots>Screenshots </h4>
<p><img width=1231 alt=image src="https://user-images.githubusercontent.com/97707804/187134477-ac56acba-7bcc-4c0a-91c5-a3a836526ba3.png"> </p>

**Comment by igorjnzl** [comment] 2022-08-31 23:13
I believe in this scenario that all AZs need to be enabled and/or disabled

**Comment by jtracey93** [comment] 2022-09-01 09:55
Thanks @aj-msft for raising this and to @igorjnzl for your inputs also.

I have tested this, this morning with Bicep and confirmed the following:

- If a public IP is created in a single specific zone, then the IP is only in that zone
- However, if a public IP is created in 2 zones, like `1` & `2` only, the IP is created across all 3 zones


## Bicep Code Example for Repro

```bicep
param pipConfig array = [
  {
    pipNumber: '1-zone'
    pipZones: [
      1
    ]
  }
  {
    pipNumber: '2-zones'
    pipZones: [
      1
      2
    ]
  }
  {
    pipNumber: '3-zones'
    pipZones: [
      1
      2
      3
    ]
  }
]

resource pip 'Microsoft.Network/publicIPAddresses@2022-01-01' = [for ip in pipConfig: {
  name: 'pip-testing-${ip.pipNumber}'
  location: 'uksouth'
  zones: ip.pipZones
  sku: {
    name: 'Standard'
    tier: 'Regional'
  }
  properties: {
    publicIPAddressVersion: 'IPv4'
    publicIPAllocationMethod: 'Static'
  }
}]
```

### Outputs 

#### `pip-test-1-zone`

```json
{
    "name": "pip-testing-1-zone",
    "id": "/subscriptions/8a703077-e97b-4943-b489-8096e5bc6deb/resourceGroups/rg-pip-testing-001/providers/Microsoft.Network/publicIPAddresses/pip-testing-1-zone",
    "etag": "W/\"54201a29-6fe9-4a58-a3f2-e02063fe3aa7\"",
    "location": "uksouth",
    "tags": {
        "DateCreated": "01/09/2022"
    },
    "zones": [
        "1"
    ],
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "e263c709-cea9-4df1-9be3-6a8efeaa9313",
        "ipAddress": "20.0.138.113",
        "publicIPAddressVersion": "IPv4",
        "publicIPAllocationMethod": "Static",
        "idleTimeoutInMinutes": 4,
        "ipTags": []
    },
    "type": "Microsoft.Network/publicIPAddresses",
    "sku": {
        "name": "Standard",
        "tier": "Regional"
    }
}
````

#### `pip-test-2-zones`

```json
{
    "name": "pip-testing-2-zones",
    "id": "/subscriptions/8a703077-e97b-4943-b489-8096e5bc6deb/resourceGroups/rg-pip-testing-001/providers/Microsoft.Network/publicIPAddresses/pip-testing-2-zones",
    "etag": "W/\"4ca66ef9-19b3-45dd-9bb8-4638b8e04877\"",
    "location": "uksouth",
    "tags": {
        "DateCreated": "01/09/2022"
    },
    "zones": [
        "1",
        "2",
        "3"
    ],
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "bef054b6-5d72-4805-9bd0-c5ce43ac3ea9",
        "ipAddress": "20.26.31.186",
        "publicIPAddressVersion": "IPv4",
        "publicIPAllocationMethod": "Static",
        "idleTimeoutInMinutes": 4,
        "ipTags": []
    },
    "type": "Microsoft.Network/publicIPAddresses",
    "sku": {
        "name": "Standard",
        "tier": "Regional"
    }
}
```

#### `pip-test-3-zones`

```json
{
    "name": "pip-testing-3-zones",
    "id": "/subscriptions/8a703077-e97b-4943-b489-8096e5bc6deb/resourceGroups/rg-pip-testing-001/providers/Microsoft.Network/publicIPAddresses/pip-testing-3-zones",
    "etag": "W/\"fc21779c-64aa-46cb-914f-a62db9da816e\"",
    "location": "uksouth",
    "tags": {
        "DateCreated": "01/09/2022"
    },
    "zones": [
        "1",
        "2",
        "3"
    ],
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "0015f218-f97c-4fcb-aa2f-a83632ac8d4d",
        "ipAddress": "20.26.168.201",
        "publicIPAddressVersion": "IPv4",
        "publicIPAllocationMethod": "Static",
        "idleTimeoutInMinutes": 4,
        "ipTags": []
    },
    "type": "Microsoft.Network/publicIPAddresses",
    "sku": {
        "name": "Standard",
        "tier": "Regional"
    }
}
```

## Suggested Fix

For @krowlandson & @matt-FFFFFF consideration.

1. Add some logic to public IP creations that if the `length` of `zones` passed in via input variables are `2 or longer` then create in all 3 zones regardless to match platform behaviour

**Comment by matt-FFFFFF** [comment] 2022-09-01 10:19
Thanks @jtracey93

I'm not sure if comfortable with explicitly going against the declared configuration for zones by deploying gin three when only two are declared. I think it would be better to be explicit and require a value for zones that is in the following set: '1', '2', '3', or '*'.

Thoughts?

**Comment by jtracey93** [comment] 2022-09-01 10:20
That makes complete sense to me @matt-FFFFFF, don't want users to be confused why they got 3 zones when they stated 2 for example. 

Happy with approach 👍

**Comment by jtracey93** [comment] 2022-09-09 15:57
Trigger ADO Sync

**Comment by krowlandson** [comment] 2022-10-13 09:41
@aj-msft I have logged this against the provider as we feel this is something which should be handled at the provider level.

https://github.com/hashicorp/terraform-provider-azurerm/issues/18741

I will leave this open for now whilst we track feedback from the provider team as we may need to implement a work-around for this within the module. My primary concern is how this will affect deployments to regions with only 2 availability zones, hence the desire to fix the provider.

**Comment by uol-amrae** [comment] 2022-10-24 11:54
for the time being, is there a suggested workaround when using 1 or 2 zones instead of 3 ? 

(or is the workaround simply: don't use availability zones / just use 3 zones [which I can't do because currently fails to build in the 3rd zone every single time])

**Comment by krowlandson** [comment] 2022-10-24 12:26
That's a great question @uol-amrae ... let me double check if/how we can set the PIP zones using the `advanced` input to set this, as that should help in the short term.

**Comment by krowlandson** [comment] 2022-10-24 21:00
@uol-amrae and @aj-msft please see the following code which you could add to the advanced block to address this issue:

```hcl
  configure_connectivity_resources = {
    # additional settings removed for brevity
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_public_ip = {
          connectivity_firewall = {
            "eastus" = {
              zones = ["1","2","3"]
            }
          }
        }
      }
    }
  }
```

Please replace `eastus` with the location you are using for your hub network.

If deploying to multiple locations, please repeat the location bound object for each location.

Based on the response to our issue on the provider, I'm not sure whether they will implement a fix on their side, so I will also re-visit whether this is something we want to add a fix for within the module.

**Comment by uol-amrae** [comment] 2022-10-25 07:26
@krowlandson - Thank you for the speedy replies.
With this 'advanced' code block in place (basically copy/pasted it into my code), it now wants to apply the Public IP config across the 3 zones (as it should be doing), so the suggested workaround does as intended

I wasn't sure how to start to tackle the problem myself, but in applying the above I've learned a little more about the TF CAF - so all is good ! will keep an eye out in future for whatever the 'fix' is too

**Comment by krowlandson** [comment] 2022-10-28 13:58
As we have provided a work-around, we are going to close this issue.

We are continuing to track this on our internal backlog and will add a more permanent fix in a future release.

**Closed by krowlandson** 2022-10-28 13:58 UTC
Labels: external bug
