### ISSUE TITLE
Bug Report Terraform plan fails due to sensitive values in azurerm_automation_account output

### ISSUE THREAD

**Issue by crosscontrol** [Azure/terraform-azurerm-caf-enterprise-scale#499] opened 2022-10-28 06:38 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.3

**azure provider**: 3.25.0

**module**: 2.4.1

### Description
Terraform plan is failing on my machine due to sensitive values in the azurerm_automation_account output.

#### Describe the bug

On my computer at least, Terraform is failing with the following error:

Error: Output refers to sensitive values
│ 
│   on outputs.tf line 109:
│  109: output "azurerm_automation_account" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true

I forked the repo and created a branch with a fix that works on my end. I removed the following [sensitive keys](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account#attributes-reference), following the convention already used to remove sensitive outputs:
* dsc_primary_access_key
* dsc_secondary_access_key

Here is the link to the branch with the changes. Please let me know if you want me to create a pull request:

https://github.com/crosscontrol/terraform-azurerm-caf-enterprise-scale/tree/fix-sensitive-output-azurerm_automation_account-output

#### Steps to Reproduce

1. Create fresh tenant
2. Reference tutorial here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Management-Resources
3. Attempt to deploy the management resources (`deploy_management_resources = true`)

#### Screenshots

![Screenshot 2022-10-27 232719](https://user-images.githubusercontent.com/31971755/198518346-a1bc4b40-c63a-4120-b156-4850ab42ab73.png)

#### Additional context

Using Terragrunt wrapper version 0.38.12.

**Comment by krowlandson** [comment] 2022-10-28 07:07
Thank you for reporting this @crosscontrol

I would guess this is due to stricter handling in the version of Terraform you are using, as we don't currently test with `v1.3` and have not observed this in our automated testing. We will be supporting this as the minimum version in the next major release.

In the meantime, I would be very grateful for you to raise a PR to add these outputs to a filter in the same way as we do for the [azurerm_log_analytics_workspace](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/ac77e2dce57cac7c148fe744972e342a80f12584/outputs.tf#L84-L96) 👍🏻 

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/ac77e2dce57cac7c148fe744972e342a80f12584/outputs.tf#L84-L96

**Comment by crosscontrol** [comment] 2022-10-28 18:26
@krowlandson, I tested my setup with Terraform v0.15.1 and I'm still getting the same error. I did some [research](https://devcoops.com/terraform-output-refers-sensitive-values/), and it looks like the secrets blocking functionality was introduced in Terraform v0.14 or so. I'm concerned as to why it's working with the tests but not on my end. I also tried downgrading the azurerm provider version to v3.18.0, same error.

I generally don't like applying fixes that I can't reliably test the before and after behavior of but in this case, I think it's good to not have those secrets in there anyway.

I'm trying not to make too much more work for you so here are a couple options forward I can think of:

1. The quick solution. If we just want to move on with it and make progress, let me know and I'll create the pull request, so the secrets are removed.
1. The not so quick solution. If we want to continue investigating why this is happening for me but not in test, here are a couple questions I have for you to help me troubleshoot:
    1. Do you know why the [secrets removal functionality was introduced](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/commit/e5d7b673488846bb85729dc2714e14be4826fe23#diff-de6c47c2496bd028a84d55ab12d8a4f90174ebfb6544b8b5c7b07a7ee4f27ec7) for [azurerm_log_analytics_workspace](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/ac77e2dce57cac7c148fe744972e342a80f12584/outputs.tf#L84-L96) in the first place?
    1. Can you tell from looking at the test environment Terraform output if the dsc_primary_access_key and dsc_secondary_access_key secrets are in there? If so, probably more reason just to apply the fix. If they aren't there, could provide another clue to what is different.

Please let me know how you want to proceed or if you have any other thoughts.

PS: Thanks for all of the awesome work you all are doing on this! It makes that [scary diagram](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/media/ns-arch-cust-expanded.png) more manageable.

**Comment by krowlandson** [comment] 2022-11-09 14:47
Thank you for your patience on this issue @crosscontrol

That logic was added due to exactly the error you are sharing, but for Log Analytics workspace. We haven't observed this for any other resource types yet so I will have to run some manual checks to see if I can identify what causes this to happen.

I will update you once I have checked this,

**Comment by krowlandson** [comment] 2022-11-25 18:05
@crosscontrol I have not been able to replicate this. Are you able to provide any further information which may help us to replicate? Thank you

**Comment by krowlandson** [comment] 2022-12-12 17:28
@crosscontrol are you able to confirm whether you reference the module as per our examples (i.e. to source from the Terraform Registry) or are cloning the module and then modifying it locally?

The only way I can reproduce this behaviour is by adding an output like the following:

```hcl
output "automation_account" {
  value     = module.test_management.azurerm_automation_account.management
}
```

This results in the following error:

```shell
╷
│ Error: Output refers to sensitive values
│
│   on outputs.tf line 25:
│   25: output "automation_account" {
│
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.
│
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
╵
```

Which can be resolved by updating as instructed:

```hcl
output "automation_account" {
  value     = module.test_management.azurerm_automation_account.management
  sensitive = true
}
```

Giving the following output:

```shell
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

automation_account = <sensitive>
```

Without trying to output the `azurerm_automation_account` values from a root module, we do not observe the error you mention.

**Comment by crosscontrol** [comment] 2022-12-12 22:27
Hi @krowlandson, I reviewed my code and I'm not explicitly referencing any outputs. I did a little bit of research on Terragrunt to see if it references all outputs but didn't find anything conclusive. I'm guessing the issue is with Terragrunt though. I want to respect your time so I don't think we should spend too much more time on this if I'm the only one having the issue.

Here are a couple thoughts for a path forward, what do you think? We can apply the change that will resolve this for my use case or leave it the way it is for now. If you all run into this in the future, you have the fix. In the meantime, I can continue from my fork.

**Comment by krowlandson** [comment] 2022-12-13 13:31
Thank you for the update @crosscontrol... it would be great to get to the bottom of this as I'm sure other customers are also using Terragrunt. We have tested the module with the versions you are using and not faced this other than when working with the outputs as in my example above.

**Closed** 2022-12-16 13:25 UTC
Labels: Needs: Author Feedback, PR-referenced
