### ISSUE TITLE
Problem with extension policy - example not working 

### ISSUE THREAD

**Issue by mlomat** [Azure/terraform-azurerm-caf-enterprise-scale#347] opened 2022-04-21 14:34 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.1.8

**azure provider**: 2.99.0

**module**: 1.1.4

### Description

**Describe the bug**

I want to extend landing zone archetype exactly in the same way as in example: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions#libarchetype_extension_es_landing_zonestmpljson

It's failing with error:

```
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
module.enterprise_scale.time_sleep.after_azurerm_policy_assignment: Destroying... [id=2022-04-21T13:42:31Z]
module.enterprise_scale.time_sleep.after_azurerm_policy_assignment: Destruction complete after 0s
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 6, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    6:   name                 = tonumber(length(each.value.template.name) > 24 ? "The policy assignment name '${each.value.template.name}' is invalid. The policy assignment name length must not exceed '24' characters." : length(each.value.template.name)) > 24 ? null : each.value.template.name
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 6, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    6:   name                 = tonumber(length(each.value.template.name) > 24 ? "The policy assignment name '${each.value.template.name}' is invalid. The policy assignment name length must not exceed '24' characters." : length(each.value.template.name)) > 24 ? null : each.value.template.name
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 6, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    6:   name                 = tonumber(length(each.value.template.name) > 24 ? "The policy assignment name '${each.value.template.name}' is invalid. The policy assignment name length must not exceed '24' characters." : length(each.value.template.name)) > 24 ? null : each.value.template.name
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 6, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    6:   name                 = tonumber(length(each.value.template.name) > 24 ? "The policy assignment name '${each.value.template.name}' is invalid. The policy assignment name length must not exceed '24' characters." : length(each.value.template.name)) > 24 ? null : each.value.template.name
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 7, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    7:   management_group_id  = each.value.scope_id
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 8, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    8:   policy_definition_id = each.value.template.properties.policyDefinitionId
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 12, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│   12:   description  = try(each.value.template.properties.description, "${each.value.template.name} Policy Assignment at scope ${each.value.scope_id}")
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 13, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│   13:   display_name = try(each.value.template.properties.displayName, each.value.template.name)
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.


│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 15, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│   15:   parameters   = try(length(each.value.parameters) > 0, false) ? jsonencode(each.value.parameters) : null
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 15, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│   15:   parameters   = try(length(each.value.parameters) > 0, false) ? jsonencode(each.value.parameters) : null
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵

│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 16, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│   16:   not_scopes   = try(each.value.template.properties.notScopes, local.empty_list)
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 17, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│   17:   enforce      = each.value.enforcement_mode
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/enterprise_scale/resources.policy_assignments.tf line 26, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│   26:       for ik, iv in try(each.value.template.identity, local.empty_map) :
│ 
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
##[error]Script failed with exit code: 1


```

**Steps to Reproduce**

1. Create main as in example. I added only:
   deploy_management_resources = true
   deploy_idenity_resources = true
   deploy_connectivity_resources = true 
  (with correct sub for each and custom config for resources) 

2. I added file: archetype_extension_es_landing_zones.tmpl.json in lib.
3. Furthermore, I tried to deploy, and I have above error.

I tested it couple times with different settings and it's failing. Exclusion is working without any problem. Do you have some test to confirm that it's still working as expected?

**Comment by krowlandson** [comment] 2022-04-21 14:53
Thank you for logging this @mlomat ... We will look into this for you.

**Comment by PaulJohnston88** [comment] 2022-04-25 19:06
Hi @mlomat - Based on the error message you provided, it looks like one of your policy assignment files has a name longer than 24 characters, which won't work. Could you check your custom policy assignment files for any where the "name" property value is longer than 24 characters and try again? I've added an example below of a policy assignment file which would cause the same error. It should just be a case of shortening this value and trying again.

![image](https://user-images.githubusercontent.com/79081054/165156191-72b6e50c-64aa-41e7-abe7-df8f72f947f6.png)

**Comment by mlomat** [comment] 2022-04-25 21:20
Hi @PaulJohnston88,

I don't have any custom policy ;) I am using out of the box and your example from Wiki. 
Custom archetype looks like this: 

```json
{
  "extend_es_landing_zones": {
    "policy_assignments": ["Deny-Resource-Locations"],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {
        "Deny-Resource-Locations": {
          "listOfAllowedLocations": ["eastus", "westus"]
        }
      },
      "access_control": {}
    }
  }
}
```

**Comment by krowlandson** [comment] 2022-04-26 08:41
@mlomat I have double checked following your steps above and am unable to reproduce this issue.

Please see the following:

![image](https://user-images.githubusercontent.com/12268562/165259202-9ded4809-0a80-4cbc-a7b7-d9499f0a4607.png)

Would you mind trying to recreate your configuration and build up the capabilities in layers to see if and where it goes wrong again?

**Comment by mlomat** [comment] 2022-04-26 08:57
@krowlandson  Try To Apply :) Plan is working fine without any error. It occurs while applying changes.

**Comment by PaulJohnston88** [comment] 2022-04-26 09:14
@mlomat I've applied the code and it's all working. Could you start over again and let us know if you're still having trouble with it?

![image](https://user-images.githubusercontent.com/79081054/165266035-07e0d9cd-6207-403c-934c-360387b18a81.png)

![image](https://user-images.githubusercontent.com/79081054/165265654-fefc74a6-4bdd-427b-97e6-c14aca97a711.png)

**Comment by krowlandson** [comment] 2022-04-26 09:24
@mlomat please can you also look to see whether a specific sequence of updates causes this error to occur?

It may be that a policy change, or something else caused by tweaking the additional settings you have may be causing this. Unfortunately Terraform isn't always great at giving a useful error message.

**Comment by krowlandson** [comment] 2022-04-26 09:26
I am also able to confirm correct creation of the expected Policy Assignment using the documented configuration and with your additional configuration settings:

![image](https://user-images.githubusercontent.com/12268562/165268704-7174100b-3e71-4082-999d-623453f8163b.png)

**Comment by mlomat** [comment] 2022-04-26 09:28
Ok, I will destroy everything and give it a second try. The sequence was that I first deploy normal setup without extension, and then I tried to add it.

**Comment by krowlandson** [comment] 2022-04-26 09:29
> Ok, I will destroy everything and give it a second try. The sequence was that I first deploy normal setup without extension, and then I tried to add it.

We will also double check this. At what point in the sequence did you add the other settings you mention? Thank you

**Comment by krowlandson** [comment] 2022-04-26 09:30
As an FYI, if you look at the updated test framework in the `main` branch, we already include sequencing in our test strategy to cover update scenarios where a customer introduces changes to the configuration so I'm fairly confident that we have this well covered but definitely want to ensure there isn't a bug we missed.

**Comment by mlomat** [comment] 2022-04-26 12:46
So I remove all resources and redeploy enterprise scale. It's still failing: 
Step 1:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/7577121/165302730-f2796639-ee16-4720-8eb5-f6da47e35c62.png">

Step 2: 
Add in lib folder: 
![image](https://user-images.githubusercontent.com/7577121/165302868-bac927cb-6b62-4d9f-a6ad-07e3b303bffe.png)

**Comment by mlomat** [comment] 2022-04-26 14:35
@krowlandson I redeploy everything again with simpler setup of ESS: 
<img width="550" alt="image" src="https://user-images.githubusercontent.com/7577121/165324697-470c8bc3-51d7-4d03-b774-93c904d09b79.png">

And after that second deployment with extension and still same error when applying changes. Please confirm that you can recreate this bug.

**Comment by krowlandson** [comment] 2022-04-30 11:24
Based on offline conversations, closing as this appears to be an environment specific issue.

Will open a new feature request based on the underlying root cause if identified.

**Closed by krowlandson** 2022-04-30 11:24 UTC
