### ISSUE TITLE
Error when setting inbound dependencies for module

### ISSUE THREAD

**Issue by krowlandson** [Azure/terraform-azurerm-caf-enterprise-scale#233] opened 2021-12-10 09:51 UTC
<h1 id=draftissuefurtherinformationrequired>DRAFT ISSUE - Further information required. </h1>
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: multiple, but tested using <code>v1.0.5</code> </p>
<p><strong>azure provider</strong>: multiple, but tested using <code>v2.89.0</code> </p>
<p><strong>module</strong>: multiple, but tested using <code>v1.0.1</code> </p>
<h3 id=description>Description </h3>
<p><strong>Describe the bug</strong> </p>
<ul>
<li>Follow up on issue identified during discussions in #214 </li>
</ul>
<p>When creating a configuration of the module which uses the output of another resource as an input, you receive an error message similar to the following: </p>
<p><img src="https://user-images.githubusercontent.com/12268562/145553170-d3f581a0-8422-4e56-a969-e9503ed99bb0.png" alt=image> </p>
<p><strong>Steps to Reproduce</strong> </p>
<ol>
<li>step 1 </li>
<li>step 2 </li>
<li>you get it… </li>
</ol>
<p><strong>Screenshots</strong> </p>
<p><strong>Additional context</strong> </p>

**Comment by manfred0191** [comment] 2021-12-13 14:23
If I can be of any help concerning this, please let me know

**Comment by manfred0191** [comment] 2021-12-20 09:08
Just in addition to what we have been discussing already: The error message above is also occuring when cleaning up the environment with terraform destroy.

**Comment by manfred0191** [comment] 2022-01-11 19:18
Hi Kevin,
any idea if this error can be fixed by time?

**Comment by krowlandson** [comment] 2022-01-12 09:00
Hi @manfred0191... my belief is that this will require a complete re-design of the resource naming convention within the module. This would have a major impact on users so we need to carefully consider the value of doing this to allow creation of a large "monolith" implementation, versus more carefully curated pipelines.

We can work around this with resource moves in Terraform state similar to the guidance we provided for management resources when [upgrading from v0.3.3 to v0.4.0](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v0.3.3-to-v0.4.0#management-resources), but this is complex and not without risk.

**Comment by jtracey93** [comment] 2022-09-09 15:57
Trigger ADO Sync

**Comment by krowlandson** [comment] 2022-10-14 07:15
Trigger ADO Sync

**Comment by matt-FFFFFF** [comment] 2023-03-03 15:40
By design but will fix in v.next

**Closed by matt-FFFFFF** 2023-03-03 15:40 UTC
