### ISSUE TITLE
'Deploy-Diagnostics-ActivityLog' definition missing from 'Deploy-Diag-LogAnalytics' policy set definition.

### ISSUE THREAD

**Issue by pmatthews05** [Azure/terraform-azurerm-caf-enterprise-scale#141] opened 2021-08-05 11:05 UTC
### Versions

**terraform**: 1.0.3

**azure provider**: Azure/caf-enterprise-scale/azurerm

**module**: 0.3.3 tags

### Description

The following definition:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_activitylog.json

It is missing from the following Policy Set Definition:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diag_loganalytics.tmpl.json

Therefore it is also missing from the es_root archetype_definitions:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/archetype_definitions/archetype_definition_es_root.tmpl.json

**Steps to Reproduce**

1. Deploy the es_root archetype_definitions to your environment.
2. Check Azure Policies
3. It hasn't been deployed to definitions, it is not part of the Policy Set Definition for 'Deploy-Resource-Diag'
4. Activity logs do not get diagnostics applied.

**Comment by krowlandson** [comment] 2021-08-06 09:07
Will investigate this upstream as we replicate policy configuration from the [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale) repository

**Comment by pmatthews05** [comment] 2021-08-06 09:41
Could you explain how the Azure/Enterprise-Scale repository ties in with this one please? As from my understanding it was just a few lines missing from those .json files.

**Comment by krowlandson** [comment] 2021-08-06 10:20
We have an automated GitHub Action called [Update Library Templates](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/.github/workflows/update-policy.yml) which pulls the policy templates from the [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale) repository and save them in the built-in [`lib`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/modules/archetypes/lib) folder.

Changes such as this need to be applied in the upstream repository, or they will be overwritten on the next sync. As such, we need to handle this Issue within the [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale) repository and then perform a new sync to pull the updates into the module.

Before we fix this, I will need to validate that this is an accidental omission or by design.

If you would prefer to "self-fix" this issue in the meantime, it's possible for you to use the custom library to store a copy of this Policy Definition with your own edits. To do this, please see the Wiki page providing guidance on [Deploy Custom Landing Zone Archetypes](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Custom-Landing-Zone-Archetypes) to better understand how to use the custom library. Although this discusses `archetype_definitions`, you can use the same logic to create and deploy custom versions of any policy, including overriding built-in ones.

For your specific ask, you would copy the [Deploy-Diag-LogAnalytics](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diag_loganalytics.tmpl.json) Policy Set Definition template into your custom library, being careful to take note of the [required file naming patterns](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions#working-with-archetype-definitions-and-the-custom-library) and then make your edits to the file. As long as you keep the `"name"` field the same as the original, the module should load your custom definition in preference to the built-in.

> **NOTE:** Just as a heads-up though, this Policy Set Definition is being updated (and renamed) in the next release which is upcoming later today. This won't include your fix, but has a number of other updates, including being renamed to `Deploy-Diagnostics-LogAnalytics`.

**Comment by pmatthews05** [comment] 2021-08-06 13:05
Thank you for the explanation, that makes more sense to me now.

I have created a "self fix", by creating a separate assignment that deploys that definition.

I'm concerned about the renaming, we have a custom archetype which is similar to the es_root, and referencing the definitions, Policy Sets and assignments that are available by default. By renaming one of the defaults this would end up breaking my custom archetype.

If instead I took a copy of all of the defaults, when it came to you adding or removing definitions to policy sets, or bug fixing etc, I wouldn't get the updates, and would need to keep my copy in sync with yours.

**Comment by krowlandson** [comment] 2021-08-06 15:10
Glad that will help for now and a great follow up question. That's why we created the option to [Expand built in archetype definitions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Expand-Built-in-Archetype-Definitions) to help in this situation. Please check that out and let me know if you need further assistance.

**Comment by krowlandson** [comment] 2021-08-11 10:59
@pmatthews05... just to give you a quick update on this.

The reason this Policy Definition is excluded from the Policy Set Definition is because we assign it independently from all other similar settings. From `v0.4.0` onwards, this Policy (along with many others) has also moved to built-in so no longer needs to be shipped as part of Enterprise-scale. As such, we have removed this from the `lib` folder.

If you look at the [`Deploy-AzActivity-Log` Policy Assignment in `v0.3.3`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/18297293ca702ce6610f0117baacdaafcc148ce8/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_azactivity_log.tmpl.json#L14) you can find the `Deploy-Diagnostics-ActivityLog` Policy Definition referenced. This has now been updated in the [`Deploy-AzActivity-Log` Policy Assignment in `v0.4.0`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/652e5dfba32609c6e65992f5beb6df9fac6d759c/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_azactivity_log.tmpl.json#L14) to use the built-in Policy Definition ID.

This Policy Assignment is included as part of the `es_root` archetype definition in both [`v0.3.3`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/18297293ca702ce6610f0117baacdaafcc148ce8/modules/archetypes/lib/archetype_definitions/archetype_definition_es_root.tmpl.json#L6) and [`v0.4.0`](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/652e5dfba32609c6e65992f5beb6df9fac6d759c/modules/archetypes/lib/archetype_definitions/archetype_definition_es_root.tmpl.json#L6) so should be applied to ALL Subscriptions within the ES hierarchy. The (now renamed) [`Deploy-Diagnostics-LogAnalytics` Policy Set Definition](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/v0.4.0/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json) is assigned via the [`Deploy-Resource-Diag` Policy Assignment](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/v0.4.0/modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_resource_diag.tmpl.json), also as part of the `es_root` archetype definition.

Hope this clarifies your question.

I will close this issue, but please feel free to reach out if you have any further questions regarding this.

**Closed by krowlandson** 2021-08-11 10:59 UTC
Labels: external bug
