### ISSUE TITLE
The Log Analytics Workspace ID spelling has changed to lower case

### ISSUE THREAD

**Issue by klausgh4836** [Azure/terraform-azurerm-caf-enterprise-scale#448] opened 2022-08-29 13:25 UTC
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>:  v1.2.5 </p>
<p><strong>azure provider</strong>: &gt;= 3.0.0 </p>
<p><strong>module</strong>: v2.3.1 </p>
<h3 id=description>Description </h3>
<h4 id=describethebug>Describe the bug </h4>
<p>Due to the fact that the notation of the workspaceID has changed, some policies are not working as expected.
The ActivitLogs for a virtual machine, for example, are no longer forwarded to the central Log Analytics workspace if it is deployed with the policy &quot;Deploy-AzActivity-Log&quot; . </p>
<p>The notation of the &quot;workspaceId&quot; has changed as follows.
Old notation:
         &quot;workspaceId&quot;:&quot;/subscriptions/xxxx/resourceGroups/xxxxx/providers/<strong>Microsoft.OperationalInsights</strong>/workspaces/bb-ccc-dev-la-management&quot; </p>
<p>New notation:
&quot;workspaceId&quot;:&quot;/subscriptions/xxxxxxxxxxx/resourcegroups/xxxxxxx/providers/<strong>microsoft.operationalinsights</strong>/workspaces/xx-aa-dev-la-management&quot;, </p>
<p>I found the workspace notation in these files. </p>
<p><code>grep -l -r 'Microsoft.OperationalInsights' modules/archetypes/ 
modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_lx_arc_monitoring.tmpl.json: 
modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_vm_monitoring.tmpl.json: 
modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_ws_arc_monitoring.tmpl.json: 
modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_azactivity_log.tmpl.json:  
modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_resource_diag.tmpl.json:
modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_vmss_monitoring.tmpl.json:</code> </p>
<h4 id=stepstoreproduce>Steps to Reproduce </h4>
<ol>
<li>Restart a virtual machine via the portal. </li>
<li>Search for the  Activity Log entries in the central log analytics workspace. The scope must be set to the virtual machine.
2.1.  kql search
<code>AzureActivity
| where TimeGenerated &gt; ago(10m)
</code> </li>
<li>Remove the category &quot;Administrative&quot; from the  &quot;Diagnostic Settings&quot; created by the policy.
3.1. Go to the virtual machine you have rebooted -&gt; Activity Log -&gt; Export Activity Log&quot; .
3.2. Select the Diagnostic Setting created by the policy.
3.3. Remove the category &quot;Administrative&quot;.
3.4. Save the new settings. </li>
<li>Add your own &quot;Diagnostic Setting&quot; to the same log analytics workspace with the category &quot;Administrative&quot; enabled.
4.1. Go to the virtual machine you have rebooted -&gt; Activity Log -&gt; Export Activity Log&quot; .
4.2. Add diagnostic setting.
4.3. Select the category &quot;Administrative&quot;.
4.4. Send to Log Analytics workspace. 
4.5 Set the same Log Analytics Workspace as the policy did. 
4.6. In the JSON View you can see the new spelling of &quot;Microsoft.OperationalInsights&quot; .
4.6 Save the new settings. </li>
<li>Restart the virtual machine via the portal. </li>
<li>Search for the  Activity Log entries in the central log analytics workspace. </li>
</ol>
<h4 id=screenshots>Screenshots </h4>
<h4 id=additionalcontext>Additional context </h4>
<p>This is a screenshot from a log analytics workspace viewed as json.
<img src="https://user-images.githubusercontent.com/77283236/187210693-643fc5bd-8bd2-4de0-8d12-e7536ec7b838.png" alt=workspace-json-view> </p>

**Comment by jtracey93** [comment] 2022-09-09 15:57
Trigger ADO Sync

**Comment by matt-FFFFFF** [comment] 2022-09-14 10:21
Hi @klausgh4836 

I have deployed a VM in my environment and I can see that the casing of the workspace is correct.

Where are you seeing the lowercase version of the resource provider name?

```bash
❯ az deployment group show --name PolicyDeployment_7260469530026173926 --resource-group testvm | jq
```

```json
{
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/testvm/providers/Microsoft.Resources/deployments/PolicyDeployment_7260469530026173926",
  "location": null,
  "name": "PolicyDeployment_7260469530026173926",
  "properties": {
    "correlationId": "00000000-0000-0000-0000-000000000000",
    "debugSetting": null,
    "dependencies": [],
    "duration": "PT4.3211031S",
    "error": null,
    "mode": "Incremental",
    "onErrorDeployment": null,
    "outputResources": [
      {
        "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/testvm/providers/Microsoft.Compute/virtualMachines/testvm/providers/Microsoft.Insights/diagnosticSettings/setbypolicy",
        "resourceGroup": "testvm"
      }
    ],
    "outputs": {},
    "parameters": {
      "location": {
        "type": "String",
        "value": "eastus"
      },
      "logAnalytics": {
        "type": "String",
        "value": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mw-demo-mgmt/providers/Microsoft.OperationalInsights/workspaces/mw-demo-la"
      },
      "metricsEnabled": {
        "type": "String",
        "value": "True"
      },
      "profileName": {
        "type": "String",
        "value": "setbypolicy"
      },
      "resourceName": {
        "type": "String",
        "value": "testvm"
      }
    },
    "parametersLink": null,
    "providers": [
      {
        "id": null,
        "namespace": "Microsoft.Compute",
        "providerAuthorizationConsentState": null,
        "registrationPolicy": null,
        "registrationState": null,
        "resourceTypes": [
          {
            "aliases": null,
            "apiProfiles": null,
            "apiVersions": null,
            "capabilities": null,
            "defaultApiVersion": null,
            "locationMappings": null,
            "locations": [
              "eastus"
            ],
            "properties": null,
            "resourceType": "virtualMachines/providers/diagnosticSettings",
            "zoneMappings": null
          }
        ]
      }
    ],
    "provisioningState": "Succeeded",
    "templateHash": "10506129510238134791",
    "templateLink": null,
    "timestamp": "2022-09-14T10:12:43.085996+00:00",
    "validatedResources": null
  },
  "resourceGroup": "testvm",
  "tags": null,
  "type": "Microsoft.Resources/deployments"
}
```

**Comment by matt-FFFFFF** [comment] 2022-09-14 10:45
I have also verified that the subscription diagnostic settings are correct:

```bash
❯ az resource show --ids /subscriptions/00000000-000-000-000-000000000000/providers/Microsoft.Insights/diagnosticSettings/subscriptionToLa --api-version 2017-05-01-preview | jq
```

```json
{
  "extendedLocation": null,
  "id": "subscriptions/00000000-000-000-000-000000000000/providers/microsoft.insights/diagnosticSettings/subscriptionToLa",
  "identity": null,
  "kind": null,
  "location": "global",
  "managedBy": null,
  "name": "subscriptionToLa",
  "plan": null,
  "properties": {
    "logs": [
      {
        "category": "Administrative",
        "categoryGroup": null,
        "enabled": true
      },
      {
        "category": "Security",
        "categoryGroup": null,
        "enabled": true
      },
      {
        "category": "ServiceHealth",
        "categoryGroup": null,
        "enabled": true
      },
      {
        "category": "Alert",
        "categoryGroup": null,
        "enabled": true
      },
      {
        "category": "Recommendation",
        "categoryGroup": null,
        "enabled": true
      },
      {
        "category": "Policy",
        "categoryGroup": null,
        "enabled": true
      },
      {
        "category": "Autoscale",
        "categoryGroup": null,
        "enabled": true
      },
      {
        "category": "ResourceHealth",
        "categoryGroup": null,
        "enabled": true
      }
    ],
    "workspaceId": "/subscriptions/00000000-000-000-000-000000000000/resourceGroups/mw-demo-mgmt/providers/Microsoft.OperationalInsights/workspaces/mw-demo-la"
  },
  "sku": null,
  "tags": null,
  "type": "Microsoft.Insights/diagnosticSettings"
}
```

**Comment by klausgh4836** [comment] 2022-09-14 11:05
Hi @matt-FFFFFF ,

I have seen the lower case spelling in the json view from the graphical user interface when I add the diagnostic setting.
Are you receiving any "Activity logs" in the defined log analytiscs workspace for example if you restart the vm?

I have done these steps in the azure portal to reproduce the issue.

1. Restart a virtual machine via the portal.

2. Search for the Activity Log entries in the central log analytics workspace. The scope must be set to the virtual machine.
- kql search AzureActivity | where TimeGenerated > ago(10m)
- The search result was empty when I tested it.

3.  Remove the category "Administrative" from the "Diagnostic Settings" created by the policy.
- Go to the virtual machine you have rebooted -> Activity Log -> Export Activity Log" .
- Select the Diagnostic Setting created by the policy.
- Remove the category "Administrative". 
- Save the new settings.

4. Add your own "Diagnostic Setting" to the same log analytics workspace with the category "Administrative" enabled.
- Go to the virtual machine you have rebooted -> Activity Log -> Export Activity Log" . 
-  Add diagnostic setting.
- Select the category "Administrative". 
- Send to Log Analytics workspace. 
- Set the same Log Analytics Workspace as the policy did. 
- In the JSON View you can see the new spelling of "Microsoft.OperationalInsights" . 
- Save the new settings.

5. Restart the virtual machine via the portal.

6. Search for the Activity Log entries in the central log analytics workspace.
  - kql search AzureActivity | where TimeGenerated > ago(10m)

Kind regards
Klaus

**Comment by klausgh4836** [comment] 2022-09-14 11:12
Hi @matt-FFFFFF ,

on the right side is the JSON View link. Here is a screen shot.
 
![image](https://user-images.githubusercontent.com/77283236/190138932-05f44297-76ec-46b9-8f8a-d16ef9c1d5ba.png)

**Comment by matt-FFFFFF** [comment] 2022-09-15 13:16
However I am trying to validate whether the activity logs are being forwarded correctly

**Comment by matt-FFFFFF** [comment] 2022-09-16 07:54
Hi @klausgh4836 

I cannot reproduce this. I have asked a colleague as well and neither of us can do so.

If you are experiencing a problem where logs are not forwarded to a central workspace then I'd suggest a support ticket might be required.

**Comment by klausgh4836** [comment] 2022-09-16 14:59
Hi @matt-FFFFFF ,

 as it seems, the way of writing is different depending on the location in which the log-analyticys workspace is created.
 I have created one in westeurope, westus, north europe and uk west. In westeurope the 'id' is in lower case, in all other locations the 'id' is in camel case.

```
az monitor log-analytics workspace list -g rg-test-log-analytics | jq '.[] | {createdDate,id,location,provisioningState,type}'
{
  'createdDate': 'Fri, 16 Sep 2022 13:57:54 GMT',
  'id': '/subscriptions/xxxxxxxxxxxxxxxxxx/resourcegroups/rg-test-log-analytics/providers/microsoft.operationalinsights/workspaces/log-analytics-test',
  'location': 'westeurope',
  'provisioningState': 'Succeeded',
  'type': 'Microsoft.OperationalInsights/workspaces'
}
{
  'createdDate': '2022-09-16T14:49:12.0727146Z',
  'id': '/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/rg-test-log-analytics/providers/Microsoft.OperationalInsights/workspaces/log-analytics-north-europe',
  'location': 'northeurope',
  'provisioningState': 'Succeeded',
  'type': 'Microsoft.OperationalInsights/workspaces'
}
{
  'createdDate': '2022-09-16T14:03:37.6153148Z',
  'id': '/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/rg-test-log-analytics/providers/Microsoft.OperationalInsights/workspaces/log-analytics-test-westus',
  'location': 'westus',
  'provisioningState': 'Succeeded',
  'type': 'Microsoft.OperationalInsights/workspaces'
}
{
  'createdDate': '2022-09-16T14:52:15.1361388Z',
  'id': '/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/rg-test-log-analytics/providers/Microsoft.OperationalInsights/workspaces/log-analytics-uk-west',
  'location': 'ukwest',
  'provisioningState': 'Succeeded',
  'type': 'Microsoft.OperationalInsights/workspaces'
}
```

**Comment by klausgh4836** [comment] 2022-09-26 12:26
Hi @matt-FFFFFF ,

 did you have time to look at the problem that in some regions the log analytics workspace is written in lower case and in some
 in camel case ? That is the reason, why the policy configures in the region westeurope the wrong log analytics workspace id.
 This causes that no Activity Logs end up in the log analytocs workspace. 

Kind regards 
Klaus

**Comment by matt-FFFFFF** [comment] 2022-09-30 18:37
Hi @klausgh4836 

Really appreciate your investigation here. Let me test further and see if I can repro.

Realistically this won't be for a week or so due to other commitments.

**Comment by krowlandson** [comment] 2022-10-06 11:08
@klausgh4836 did you manage to log a support ticket for this and get any feedback?

In our experience, Azure is largely case insensitive so it's not common for something like this to create an issue on the platform. A more common issue we observe is when Terraform (which is case sensitive) has config with a different case to what is returned from the platform, resulting in it continually trying to update the target resource to match the specified case. However this isn't the issue in this case.

Thank you for your on-going support on this issue.

**Comment by krowlandson** [comment] 2022-10-10 15:34
@klausgh4836 I've done a bit of further testing as we're keen to find a resolution for you.

Using the module, I have implemented the management resources into the following locations:

- `westeurope`
- `northeurope`
- `eastus`
- `westus`
- `ukwest`

Looking at the deployed resources in the Portal, all of these return the Log Analytics workspace resource ID in lowercase as per the following screenshots:

## westeurope

![image of Log Analytics workspace JSON properties in West Europe showing resource ID in lowercase](https://user-images.githubusercontent.com/12268562/194899579-1b2df8ca-1d10-4c8e-8aae-0f4c8af3953f.png)

## northeurope

![image of Log Analytics workspace JSON properties in North Europe showing resource ID in lowercase](https://user-images.githubusercontent.com/12268562/194900104-b881b602-9a49-4b8e-9111-7798817527bc.png)

## eastus

![image of Log Analytics workspace JSON properties in East US showing resource ID in lowercase](https://user-images.githubusercontent.com/12268562/194900272-afc4784d-2e77-4c7d-99f8-3fc8c8c2af4e.png)

## westus

![image of Log Analytics workspace JSON properties in West US showing resource ID in lowercase](https://user-images.githubusercontent.com/12268562/194899379-449f7fe0-c4b9-4c8f-8ab7-5e48acf917f7.png)

## ukwest

![image of Log Analytics workspace JSON properties in UK West showing resource ID in lowercase](https://user-images.githubusercontent.com/12268562/194900187-86a27eee-3107-4b20-b4fe-336c3128e86a.png)

Upon further investigation I can however see the behaviour you are observing regarding different casing being returned by the Azure REST API. This is what results in the different casing you observe in Azure CLI (_and is also present in Azure PowerShell_).

However, none of this is behaviour that we can control within either this module, or the Azure provider for Terraform. I also do not believe this to be something we can or need to allow for in the underlying policy as the platform is not case sensitive when referencing resources by ID. This can be seen in the following REST API request where you can see I have changed the casing from `microsoft.operationalinsights` to `microsoft.OPERATIONALinsights` to show this:

![image of API request with incorrect casing](https://user-images.githubusercontent.com/12268562/194902985-ae00d20f-7fc9-423a-865e-9564ddcabd5e.png)

As such, I am going to close this issue and suggest you continue your investigation by [creating an Azure support request](https://learn.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Closed by krowlandson** 2022-10-10 15:34 UTC

**Comment by krowlandson** [comment] 2022-10-14 07:19
Trigger ADO Sync
