### ISSUE TITLE
Upgrade es-caf azurerm provider from 3.116.0 to 4.0.0

### ISSUE THREAD

**Issue by MrKeithM** [Azure/terraform-azurerm-caf-enterprise-scale#1157] opened 2024-10-16 13:39 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: hashicorp/ - version = "3.116.0"

**azure provider**: azurerm

**module**:

### Description

Im trying to upgrade the azurerm provider in my es-caf-module from version from "3.116.0" to "4.0.0" when the plan runs I get this error:

╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/enterprise_scale/resources.connectivity.tf line 58, in resource "azurerm_subnet" "connectivity":
│   58:   private_endpoint_network_policies_enabled     = each.value.template.private_endpoint_network_policies_enabled
│ 
│ An argument named "private_endpoint_network_policies_enabled" is not
│ expected here.

this error is based on a file on the resources.connectivity.tf file within the >>> .terraform/modules/enterprise_scale/resources.connectivity.tf fileany changes to this doesnt seem to be picked up. I have commented it out with no good results.

#### Steps to Reproduce

1) upgrade hashicorp/azurerm version from version "3.116.0" to version "4.0.0"
2) error should show up on the planning section citing an unrecognised arguement

#### Additional context

Im a rookie at managing ES-CAF and providers please let me know if this question is inapporpiate for this forum. Many Thanks.

**Comment by kewalaka** [comment] 2024-10-18 21:54
This is a duplicate of https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/1123

As noted on that issue, support for AzureRM v4 is currently targetted for v7 of this module.

**Comment by MrKeithM** [comment] 2024-10-18 21:59
> This is a duplicate of [#1123](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/1123)
> 
> As noted on that issue, support for AzureRM v4 is currently targetted for v7 of this module.

apoligies for the duplicate question, will track the updates on the referenced issue 👍🏾

**Comment by matt-FFFFFF** [comment] 2024-11-14 17:25
CLosing as dupe

**Closed by matt-FFFFFF** 2024-11-14 17:25 UTC
