### ISSUE TITLE
Bug Report - `management_group_id` deprecated in favour of `management_group_name`

### ISSUE THREAD

**Issue by dgteixeira** [Azure/terraform-azurerm-caf-enterprise-scale#315] opened 2022-03-30 10:12 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.1.7

**azure provider**: v2.88.1

**module**: v1.1.4

### Description

**Describe the bug**

When trying to update from version v1.1.3 to v.1.1.4 (without any other change), I get a deprecated warning when performing a terraform validate.

IF I change the version back to 1.1.3, the warning disappears.

```bash
✗ tf validate
╷
│ Warning: Argument is deprecated
│
│   with module.enterprise_scale.azurerm_policy_definition.enterprise_scale,
│   on .terraform/modules/enterprise_scale/resources.policy_definitions.tf line 12, in resource "azurerm_policy_definition" "enterprise_scale":
│   12:   management_group_id = try(basename(each.value.scope_id), null)
│
│ Deprecated in favour of `management_group_name`
│
│ (and one more similar warning elsewhere)
╵
Success! The configuration is valid, but there were some validation warnings as shown above.
```

**Steps to Reproduce**

1. Change module version from v1.1.3 to v1.1.4
2. Perform `terraform validate`
3. Get warning

**Comment by krowlandson** [comment] 2022-03-30 10:30
Looking at this now. Thank you for bringing this to our attention

**Comment by krowlandson** [comment] 2022-03-30 10:54
@dgteixeira ... we have had a quick look at this and realised that we created the hotfix release using the wrong commit. We have fixed this, however this was not the cause of the issue.

If you update your provider version from `v2.88.1` to the latest supported version `v2.99.0` you will see this behaviour consistently across both versions of the module.

We already have a fix for this in `main` which will be included in release `v1.2.0`. At this point, we will also increase the minimum supported version to address some other issues you may face on running `terraform destroy`.

Hope this helps. I will close this issue as this is being addressed in the next release.

**Closed by krowlandson** 2022-03-30 10:54 UTC

**Comment by dgteixeira** [comment] 2022-03-30 11:00
hey @krowlandson,
Thanks for the fast reply!

We will wait for the module release `v1.2.0` and then update the module and the provider together.

Thanks again and best regards,
Diogo Teixeira

**Comment by krowlandson** [comment] 2022-03-30 12:31
Sounds like a good plan. Thank you for your understanding.

- Also linking to duplicate issue for tracking #272
