### ISSUE TITLE
Please confirm which resource types can be configured with "Advanced" settings?

### ISSUE THREAD

**Issue by kahawai-sre** [Azure/terraform-azurerm-caf-enterprise-scale#357] opened 2022-05-02 20:57 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

All / Main

### Description

Does the code below limit the specific resource types that are supported for configuring Advanced settings:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/246cf7de44369b2a40a1b07fafdd8b8b792e7c35/modules/connectivity/variables.tf#L316

If so, can this please be extended e.g. add support for "azurerm_private_dns_zone_virtual_network_link"?

Many thanks!

**Comment by matt-FFFFFF** [comment] 2022-05-03 16:23
Hi @kahawai-sre 

You are correct that the variable validation prevents customization of azurerm_private_dns_zone_virtual_network_link resources. I will address this is a hotfix release.

Since this is a duplicate of #348 I will close this issue

**Closed by matt-FFFFFF** 2022-05-03 16:23 UTC
Labels: Needs: Triage :mag:
