### ISSUE TITLE
Policy Assignment Deploy-Resource-Diag -> logAnalytics Subscription ID is 00000000-0000-0000-0000-00 0000000000

### ISSUE THREAD

**Issue by XristophD** [Azure/terraform-azurerm-caf-enterprise-scale#607] opened 2023-02-08 15:01 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
v1.3.6
**azure provider**:
v3.42.0
**module**:
3.1.2

### Description
We have deployed Enterprise Scale Management and Connectivity resources to the same subscription. 
Subscription IDs are set for both management and connectivity subscription, both to the same ID. 

We set the subscription ID to be used for connectivity and management in our provider:
```
provider "azurerm" {
  features {}
  subscription_id = "<hub-subscription-id>"
}
```

And configure the CAF-module as below:

```
data "azurerm_client_config" "core" {}

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "3.1.2"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm
    azurerm.management   = azurerm
  }

  #... more configuration

  deploy_management_resources    = true
  subscription_id_management     = data.azurerm_client_config.core.subscription_id
  configure_management_resources = local.configure_management_resources

  deploy_connectivity_resources    = true
  subscription_id_connectivity     = data.azurerm_client_config.core.subscription_id
  configure_connectivity_resources = local.configure_connectivity_resources

  #... more configuration
}
```

#### Describe the bug
After deployment, the parameter _logAnalytics_ for policy Assignment _Deploy-Resource-Diag_ is pointing to a log analytics workspace with a subscription ID 00000000-0000-0000-0000-00 0000000000, as you can see in first screenshot.

Expected behavior would be to see the Subscription ID for the Management Subscription, set with _subscription_id_management_. 

Changing it manually within the Policy Assignment in the portal works, but the next _terraform plan_ wants to overwrite it again with the Null-Guid, see second screenshot. 

#### Steps to Reproduce

1. Configure as described above, whereas management and connectivity subscription are the same
2. Deploy
3. Check Parameter Value _logAnalytics_ for Deploy-Resource-Diag

#### Screenshots

![image](https://user-images.githubusercontent.com/10231267/217562686-e572dff8-4874-4ce7-9599-92daba6c08e4.png)

![image](https://user-images.githubusercontent.com/10231267/217563568-12c22242-0c81-4725-808f-2e0334860c71.png)

#### Additional context
The issue seems to be related to this older issue: 
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/85

I couldn't find an error in our configuration and would be happy about assistance on this issue.

**Comment by luke-taylor** [comment] 2023-02-08 16:12
For `subscription_id_management` try using the raw string instead of `data.azurerm_client_config.core.subscription_id` just so we know there's nothing wrong with the data lookup. 

If that does work, I would lean towards passing the subscription ID as a variable as would be best practice if you start to introduce multiple subscriptions in your deployment.

**Comment by XristophD** [comment] 2023-02-09 08:56
Hello @luke-taylor , thank you for your fast response. 
Changing the ID to a raw string (for both assignments) still brings the same result.

```
  deploy_management_resources    = true
  subscription_id_management     = "<Subscription-ID>"
  configure_management_resources = local.configure_management_resources

  deploy_connectivity_resources    = true
  subscription_id_connectivity     = "<Subscription-ID>"
  configure_connectivity_resources = local.configure_connectivity_resources
```

A new _terraform plan_ still tries to set the parameter to the Null-Guid for subscription on the LA workspace, same to my second screenshot in my initial post. 

An interesting point I guess is, that the following three Policy Assignments work as expected: 
- Deploy-VM-Monitoring
- Deploy-VMSS-Monitoring
- Deploy-AzActivity-Log 

All three are handled the same way as _Deploy-Resource-Diag_ in the following file: 
- terraform-azurerm-caf-enterprise-scale\modules\management\locals.tf

```
Deploy-VM-Monitoring = {
  logAnalytics_1 = local.log_analytics_workspace_resource_id
}
Deploy-VMSS-Monitoring = {
  logAnalytics_1 = local.log_analytics_workspace_resource_id
}
Deploy-AzActivity-Log = {
  logAnalytics = local.log_analytics_workspace_resource_id
}
Deploy-Resource-Diag = {
  logAnalytics = local.log_analytics_workspace_resource_id
}
```

Therefore, for me it looks like the ID is set correctly during initalization, but the error is somewhere deeper in the assignment to the parameter of the PolicyAssignment. I was trying to follow down the rabbit hole of policy assignments and local variable overrides, but couldn't find any mismatch here. Also I was not able to see any issue with the PolicySet or therefore its parameters itself.

My question would be if you have any hint to debug this issue, or if you could confirm it working on a similar setup than mine (single subscription, only Identity and Management deployed).

**Comment by XristophD** [comment] 2023-02-09 09:15
Ok, I guess I found the issue. I am not sure if this behaves "as designed", but it makes sense now. 

I was configuring an archtype override for "es_root" to (temporarily) disable the AKSLogAnalyticsEffekt. 

```
archetype_config_overrides = {

    root = {
      archetype_id = "es_root"
      parameters = {
        Deploy-Resource-Diag = {
          # Currently, this will set kube-audit logs to be sent to Log Analytics Workspace, which is quite excessive and therefore expensive.
          # TODO: this is just a workaround, better to define custom Archetype where this is set directly for kube-audit
          # 
          AKSLogAnalyticsEffect = "Disabled"
        }
      }
      access_control = {}
    }
    landing-zones = {
      archetype_id = "es_landing_zones"
      parameters = {
        Deny-Subnet-Without-Nsg = {
          effect = "Audit"
        }
        Enforce-AKS-HTTPS = {
          effect = "Audit"
        }
      }
      access_control = {}
    }
  }
```

With this override, the archetype-override coming from the management module within the Enterprise Scale module where the ID for the Log Analytics workspace is set. Therefore the deployment went back to the default values here, where the Null-Guid is part of it. 

The documentation on overriding particular Policy Assignment parameters was pretty clear to use overrides, e.g. for the [Deny-Subnet-Without-NSG documentation](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Set-parameter-values-for-Policy-Assignments#option-archetype_config_overrides-input-variable)


My understanding was, that default values would work all the time, but with a default value of an Null-Guid this is not the case. From a design perspective I would have expected that the LA Workspace Guid is set somewhere else, where it is not easily overwritten.

**Comment by luke-taylor** [comment] 2023-02-09 11:31
@XristophD  Yes well spotted, this also applies to any policy containing the resource ID for the Log Analytics Workspace. the variable `archetype_config_overrides` will supercede anything before it and will 'merge' the parameters specified within the variable with the original _defaults_ for the policy assignment, which in this case would indeed include the default subscription Id (000...) for the `logAnalytics` parameter. To prevent this, the full LAW Id will need to be specified if you want to override the original parameters set for that policy.  

The LAW is somewhat of a special case where we are pre-emptively anticipating its creation by setting the, in a sense, future resource Id for the LAW itself, it has to be this way since it's better to ensure all policies and governance are already in place before resources are deployed so that when resources enter the environment polices will kick in straight away.  Therefore, there would be no possible default value for the `logAnalytics` parameter that would ever work unfortunately.

**Comment by XristophD** [comment] 2023-02-10 08:29
@luke-taylor , I understand your point, but to be honest I was a bit puzzled experiencing this behavior on overwriting defaults. 
As of my understanding, a default value should be a valid value, if no valid default can be set, a null-value should be set and therefore an exception should be raised deploying the template - with this, a user would see this a bit earlier. 

I was more or less accidentally stumbling across the wrongly set Log Analytics Workspace, I would guess there are many customers out there pointing to a Null-Guid non-existing workspace at the moment. 

Anyway, a hint in the documentation of archetype_config_overrides would be helpful.

**Comment by krowlandson** [comment] 2023-02-10 13:07
@XristophD we may be able to go one better, and thank you for the help on this one @luke-taylor 👍🏻 

The initial logic was designed with an order of precedence (which will need to be retained) which merges parameter values in the following order:

1. Default values from within the base definition or initiative
2. Values defined within the assignment template
3. Values managed by the module (such as the `logAnayltics` value you note in this issue)
4. Values provided within the `archetype_config.parameters` object from an archetype definition template
5. Values provided within the `archetype_config.parameters` object from either the `archetype_config_overrides` of `custom_landing_zones` input

Because of the way policy assignments work, the default values from within the policy definition or initiative [list item 1] will always apply unless explicitly overridden in the assignment. We cannot and do not change this behaviour.

What we then do is to merge the values defined within the assignment template [list item 2] with a pre-merged map of all other scoped values [list items 3, 4 & 5].

As these are merged on a "per-policy" basis, this makes it an "all or nothing" scenario when you provide custom values via list items 3, 4 & 5.

I've just had a play with the code logic this morning and we should be able to update this so we merge at a per-parameter basis instead. I believe this would give the behaviour you are asking for and should be non-impacting for existing customers who to date would've had to define all required parameters anyway.

Would updating this behaviour as described make it work in a more instinctive manner?

**Comment by XristophD** [comment] 2023-02-10 14:56
Hello @krowlandson, thank you for your information and input on this one. 
Your described way of merging on per-parameter basis sounds like the behavior I would have expected in the first place. Thank you for explaining the steps so detailed and trying to find a solution on this. I appreciate the super fast feedback and patient explanation of both of you, @krowlandson and @luke-taylor .

**Closed** 2023-02-14 09:57 UTC
Labels: enhancement, PR-referenced
