### ISSUE TITLE
Subscription flips between platform management group and management management group.

### ISSUE THREAD

**Issue by ofbjansen** [Azure/terraform-azurerm-caf-enterprise-scale#151] opened 2021-08-19 11:42 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.4

**azure provider**: 2.71.0

**module**: 0.4.0

### Description

**Describe the bug**

When using a subscription only on platform and not on management management group (and probably but not tested on the identity or connectivity) and you have set the subscription_id_management variable, the subscription flips by every apply. So when the subscription is on the platform management group the apply will move to the management management group. 

**Steps to Reproduce**

In the module enable the management resources and set the subscription_id_management variable with the subscription needed to fill in the policies with platform subscription. In the subscription_id_overrides set the platform with the same subscription.

Then deploy the resources. All resources will be deployed and the policies that contain management resources information will contain the subscription.

Don't change the configuration and do either a plan or apply. The result will be that the subscription will be moved to the management management group. 

If you apply the move and do the same the results will be to move the subscription back to platform.

**Additional context**

We only set subscriptions to platform and landing zone management groups and not to all the management groups separately. When I don't fill in the subscription_id_management, the policy assignments that contain linking to management resources will have the wrong subscription in the resource id. When create the assignments correctly, but the subscription flips. If there is another way to ensure the policies are created correctly it would help. Hope you can change, fix or advise.

**Comment by krowlandson** [comment] 2021-08-19 12:05
Interesting issue... please can I confirm why you are trying to assign the `management` Subscription to the `platform` Management Group? I assume you have the association to `platform` declared via the `subscription_id_overrides` input variable?

By design, we have included logic to handle a race condition between `connectivity`, `identity` and `management` but not any others.

**Comment by krowlandson** [comment] 2021-08-19 14:50
Just to add, if you are trying to implement the [Trey Research](https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md) scenario, we don't currently support this in the Terraform module but would be open to adding this to our backlog if this is what you are asking for?

![Deploy Enterprise-scale for small enterprises](https://raw.githubusercontent.com/Azure/Enterprise-Scale/main/docs/reference/treyresearch/media/es-lite.png)

**Comment by ofbjansen** [comment] 2021-08-19 19:34
> Interesting issue... please can I confirm why you are trying to assign the `management` Subscription to the `platform` Management Group?
> 
> From an architectural perspective, the reason each Subscription has a dedicated Management Group is to ensure the correct policies are assigned to each Subscription in a way that the Subscription "Owners" cannot remove these policies unless they are also Owners of the parent Management Group(s). This is part of how the governance model is enforced.
> 
> By design, we have included logic to handle a race condition between `connectivity`, `identity` and `management` but not any others.

I am trying to get all the management, connectivity and identity resources in the subscription in the platform management group. Short the  Trey Research model you mentioned. It could change in the future so we chose to use platform as the placeholder for now and add relevant policies.

**Comment by krowlandson** [comment] 2021-08-23 10:22
OK, that makes sense but isn't how we have built the logic.

If you are happy to follow our logic, simply specify the same Subscription ID in one or more of `subscription_id_connectivity`, `subscription_id_identity` and `subscription_id_management` and the module will place the Subscription in the expected Management Group. Do not use this in combination with `subscription_id_overrides` though.

Subscription placement is based on the following order or preference:
1. Management
2. Connectivity
3. Identity

If not, we currently don't have a mechanism to go up to `Platform` and I'm unsure whether this is something we plan to support as Trey Research (mentioned above) is a very specific implementation of Enterprise-scale.

Instead, my current thought is to add a mechanism (date TBC) which would ensure the archetypes from each "merged scope" are applied on the same Management Group as the Subscription. For example, if you have both `management` and `connectivity` resources in the same Subscription, we would merge the `management` and `connectivity` archetypes on the `management` Management Group. `identity` would continue to be a dedicated Management Group with the `identity` archetype applied.

This approach ensures that the correct governance settings are applied on the Subscription. For `management`, `connectivity` and `identity` these are all intentionally designed to be a 1-2-1 relationship as some Policy Assignments are specific to a single Subscription. We don't assign these to the Subscription directly though, as the inheritance based approach is more secure (a Subscription `Owner` cannot remove inherited policies).

I guess it may also make sense to remove the unused Management Groups, but I need to be careful not to implement "features" which are inconsistent with the architecture, or our non-Terraform based implementations.

Hope this helps?

**Comment by ofbjansen** [comment] 2021-08-24 20:43
Thank you @krowlandson. It makes sense to wait for Trey Research setup to come by. For now the deployment is not something we do on a daily basis so we can work with manual adjustments and have it documented.

One question though, will the Trey Research approach be added in this module or will it be created in a different module?

**Comment by krowlandson** [comment] 2021-08-24 21:33
Nothing confirmed at this point regarding Trey Research, however I can look into the feasibility of adding an option to "roll-up to `platform`" when I look at providing a mechanism to consolidate `archetype_definitions` in a single platform Subscription deployment. No ETA on this though as currently focused on updating the Wiki docs to allow users to utilise the current capabilities more easily.

**Comment by krowlandson** [comment] 2021-09-30 18:53
Re-categorising as feature request for the capabilities described in my last update.

**Comment by matt-FFFFFF** [comment] 2021-11-26 14:48
This will be fixed when the following is implemented

* #223

**Closed by matt-FFFFFF** 2021-11-26 14:48 UTC
Labels: enhancement
