### ISSUE TITLE
Inability to assign policy from "nested" module

### ISSUE THREAD

**Issue by GoodDingo** [Azure/terraform-azurerm-caf-enterprise-scale#152] opened 2021-08-20 21:33 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `1.0.5`

**azure provider**: `2.73.0`

**module**: `0.4.0`

----

### Description

**When deploying module in several steps and keeping all policy definitions in parent MG, I'm unable to attach those custom policies in nested module.**

I'm deploying ESLZ in several stages.
1) basic module deployment with several policy exclusions and custom policy initiative for tagging
2) this gets deployed correctly, policy lives under top MG, all is good
3) then I want to deploy just 2 new MG implemented using calling module twice with `deploy_core_landing_zones = false`
4) here during the deployment everything falls apart

<details>
  <summary>code for `main.tf`</summary>

```hcl
# main.tf

data "azurerm_client_config" "current" {}

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  root_parent_id = data.azurerm_client_config.current.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.root}/lib"
}

# plus there is a definition of custom Policy Initiative that gets deployed 
```

</details>

<details>
  <summary>code for `dependent.tf`</summary>

```hcl
# dependent.tf, it is NOT deployed in the same statefile, it is deployed in next statefile after the main is deployed
# hence no "depends_on enterprise_scale" is  here

module "eslz_team_cloudteam" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  root_parent_id            = "${var.root_id}-landing-zones"
  root_id                   = var.root_id
  deploy_core_landing_zones = false
  library_path              = "${path.root}/lib"

  custom_landing_zones = {
    "${var.root_id}-lz--cloudteam" = {
      display_name               = "${upper(var.root_id)} :: Cloud Team"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
  }
}


module "eslz_team_cloudteam_dev" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  root_parent_id            = "${var.root_id}-lz--cloudteam"
  root_id                   = var.root_id
  deploy_core_landing_zones = false
  library_path              = "${path.root}/lib"

  custom_landing_zones = {
    "${var.root_id}-lz--cloudteam-dev" = {
      display_name               = "${upper(var.root_id)} :: Cloud Team - Dev"
      parent_management_group_id = "${var.root_id}-lz--cloudteam"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "generic_env_dev"    # <-- this triggers assignment
        parameters     = {}
        access_control = {}
      }
    }
  }

  depends_on = [
    module.eslz_team_cloudteam,
  ]
}

```
</details>

<details>
  <summary>code for policy assignement living in dependent `lib/`</summary>

```yaml
# lib/policy_assignments/policy_assignment_company_global_tagging.yaml

generic_env_dev:
  policy_assignments:
    - Deny-Resource-Locations  # this works
    - Company-Global-Tagging  # this fails, it is custom initiative living in root_id MG
  policy_definitions: []
  policy_set_definitions: []
  role_definitions: []
  archetype_config:
    parameters:
      Deny-Resource-Locations:
        listOfAllowedLocations:
          - eastus
          - westus
    access_control: {}
```

```yaml
# lib/policy_assignments/policy_assignment_company_global_tagging.yaml

name: Company-Global-Tagging
type: Microsoft.Authorization/policyAssignments
apiVersion: '2019-09-01'
properties:
  description: All resources should conform to global Company Tagging convention.
  displayName: Assign policies for Company Cloud Tagging.
  notScopes: []
  parameters: null

  # I've tried many things here, nothing worked for me
  policyDefinitionId: >-
    /providers/Microsoft.Management/managementgroups/cloud/providers/Microsoft.Authorization/policySetDefinitions/Company-Global-Tagging-Initiative
  scope: '${current_scope_resource_id}'
  enforcementMode: Default
location: '${default_location}'
identity:
  type: SystemAssigned
```
</details>

**Steps to Reproduce**

<details>
  <summary>Having those files in dependent dir:</summary>

```
├── lib
│   ├── archetype_definitions
│   │   └── archetype_definition_generic_env_dev.yml
│   └── policy_assignments
│       └── policy_assignment_company_global_tagging.yml
├── team_cloud.tf
├── terraform.tf
└── variables.tf
```
</details>

1. during `terraform plan` I'll get

```
│ Error: Invalid for_each argument
│
│   on .terraform/modules/eslz_team_cloudteam_dev/locals.policy_assignments.tf line 158, in data "azurerm_policy_definition" "external_lookup":
│  158:   for_each = local.azurerm_policy_definition_external_lookup
│     ├────────────────
│     │ local.azurerm_policy_definition_external_lookup will be known only after apply
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the
│ -target argument to first apply only the resources that the for_each depends on.
```

---

What I basically want is to define the Policy initiative once on the top MG and then assign it on leaf MG (the bug is about inability to do so, but maybe it's my fault).

Work-around is to define Policy Initiative many times, always on the leaf MG and assign it there, it works, but it feels wrong to have total same definition so many times.

Thank you very much with any guidance, I've tried everything that I know (which is very little to be frank).
Feel free to close this issue and maybe writing a wiki article how to do it correctly. :-)

Appreciate all your work, and very well thought out design. Kudos

**Comment by krowlandson** [comment] 2021-08-23 10:06
Thank you for raising this issue @GoodDingo... this is a really interesting scenario, plus great to see you making use of our support for YAML in the library!

Although we didn't anticipate someone using individual declarations of the module "per Management Group" as in your example, this should work as you describe.

Looking at the error, I believe it is finding `Company-Global-Tagging-Initiative` without any problem. Instead, I believe it's struggling to find one of the dependent Policy Definitions within the Initiative (or one which is completely unrelated). That in itself is an interesting situation though, as the Initiative would fail to deploy (Azure error, not Terraform) if all dependent Policy Definitions were not present.

I cannot see anything wrong with your `lib/policy_assignments/policy_assignment_avast_global_tagging.yaml` file, but as long as you are declaring the correct [same] `root_id` across each deployment, you should be able to use the template file variables to auto-populate the correct scope using:

```yml
  policyDefinitionId: ${root_scope_resource_id}/providers/Microsoft.Authorization/policySetDefinitions/Company-Global-Tagging-Initiative
```

The point at which this has failed is where the module is looking up the Role Definitions declared within each Policy Definition. Specifically for a Policy Definition which it doesn't already know about (hence `_external_lookup`).

Before I try to over-think this or offer workarounds which may just mask the root cause, please can you confirm whether each deployment is being run under the same credentials? i.e. can the identity used to deploy `eslz_team_cloudteam_dev` also read the Policy Definitions and Initiatives at the `root` scope?

**Comment by GoodDingo** [comment] 2021-08-23 10:18
Hello @krowlandson and thank you for the reply.

I **am** deploying with the same credentials (owner of Tenant Root Group).

I will try to minimize the two separate deployment modules, try to deploy and then update my little confused description at the end of this week (Thu/Fri), then I'll send more organized info, full `.tf` files + screenshots... so that you have working minimal example to try/validate it should work (or to find my error).

(_The motivation for the split was that we were trying to minimize blast radius by having multiple storage accounts and states - one base + management&identity&connection and each for one "customer" (internal company self-contained team or product). We would really like to keep the states separate and not have it in one huge basket. That would make each new automated deployment more stressful... 😅_)

**Comment by krowlandson** [comment] 2021-08-23 10:53
That all makes sense, and is exactly why we provided the ability to do a [nested deployment](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Using-Module-Nesting) so great to see you making use of this.

I'm sure this goes without saying, but in order for a nested deployment to work, all referenced `Policy Definitions` or `Policy Set Definitions` must already exist if not deployed by that specific instance of the module. This is due to the way we perform the `roleDefinitionIds` lookup.

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/bea345a52395926c10220e3980e60501460bc33e/locals.policy_assignments.tf#L156-L162

I'll see whether I can reproduce this error, so any additional details you can share would be greatly appreciated. We already have at least partial code coverage for this in the test framework, but that is all within the same pipeline. I don't believe that should matter though, so will check it out.

Meanwhile, the "official" workaround for this would be to use the [Override Module Role Assignments](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Override-Module-Role-Assignments) capability, which should supress the need to perform a lookup for the specified policies in the first place.

**Comment by krowlandson** [comment] 2021-09-01 08:54
@GoodDingo just wanted to check how you are getting on with this? Do you require further assistance, or are you happy for us to close this issue?

**Comment by GoodDingo** [comment] 2021-09-07 12:30
I was able to create two (kinda) minimal examples, one that passes, one that fails (suspect is `depends_on`).

What is the best way to post it?  Markdown and files or attach `.tar`/`.zip` file?

**Closed** 2022-02-10 19:02 UTC
Labels: documentation, Needs: Author Feedback, Status: No Recent Activity
