### ISSUE TITLE
Policy assignments using User Assigned Identities

### ISSUE THREAD

**Issue by dbgrz** [Azure/terraform-azurerm-caf-enterprise-scale#655] opened 2023-03-23 08:48 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As stated in atleast this issue:
Policy assignments using User Assigned Identities are not supported #304

it seems this is now available. A quick check on the azurerm provider documentations also suggests using UserAssigned now
https://github.com/hashicorp/terraform-provider-azurerm/issues/14087
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_assignment

#### Is your feature request related to a problem?
We want to use userassigned identities for our policies.

#### Describe the solution you'd like
Implement the features from the azurerm provider

**Comment by matt-FFFFFF** [comment] 2023-03-23 11:05
duplicate of #500 we are considering for next major release

**Closed by matt-FFFFFF** 2023-03-23 11:05 UTC
Labels: duplicate, enhancement
