### ISSUE TITLE
Feature Request - Custom naming of Management Groups

### ISSUE THREAD

**Issue by erisnar** [Azure/terraform-azurerm-caf-enterprise-scale#533] opened 2022-12-01 10:52 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

From the [Azure docs](https://learn.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/enterprise-scale/testing-approach#example-scenarios-and-outcomes) describing canary scenario:

 *"Note*
 
 *The canary environment management group display names can be the same as the production environment management group display names. This might cause confusion for users. Because of this, we recommend to append the name "canary" to the display names, as well as to their IDs."*

In the following file, locals are defined to configure Management Groups including ```display_name```. See https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/locals.management_groups.tf#L186.

```terraform
# The following locals are used to define the core Enterprise
# -scale Management Groups deployed by the module and uses
# logic to determine the full Management Group deployment
# hierarchy.
locals {
  # Mandatory core Enterprise-scale Management Groups
  es_core_landing_zones = {
    (local.root_id) = {
      display_name               = local.root_name
      parent_management_group_id = local.root_parent_id
      subscription_ids           = local.es_subscription_ids_map[local.root_id]
      archetype_config           = local.es_archetype_config_map[local.root_id]
    }
    "${local.root_id}-decommissioned" = {
      display_name               = "Decommissioned"
      parent_management_group_id = local.root_id
      subscription_ids           = local.es_subscription_ids_map["${local.root_id}-decommissioned"]
      archetype_config           = local.es_archetype_config_map["${local.root_id}-decommissioned"]
    }
    "${local.root_id}-sandboxes" = {
      display_name               = "Sandboxes"
      parent_management_group_id = local.root_id
      subscription_ids           = local.es_subscription_ids_map["${local.root_id}-sandboxes"]
      archetype_config           = local.es_archetype_config_map["${local.root_id}-sandboxes"]
    }
    "${local.root_id}-landing-zones" = {
      display_name               = "Landing Zones"
      parent_management_group_id = local.root_id
      subscription_ids           = local.es_subscription_ids_map["${local.root_id}-landing-zones"]
      archetype_config           = local.es_archetype_config_map["${local.root_id}-landing-zones"]
    }
    ...
}
```

How do we append Canary to ```display_name``` as the documentation recommends?

#### Describe the solution you'd like

We suggest adding a variable to ```display_name``` for each Management Group to allow custom naming.

For example, changing ```display_name``` of root is allowed:

```terraform
    (local.root_id) = {
      display_name               = local.root_name
      parent_management_group_id = local.root_parent_id
      subscription_ids           = local.es_subscription_ids_map[local.root_id]
      archetype_config           = local.es_archetype_config_map[local.root_id]
    }
```

**Comment by krowlandson** [comment] 2022-12-01 22:12
Happy to look at this @erisnar... would it suffice to include a variable such as `mg_suffix` to optionally add a suffix to all default management groups?

Alternatively, we were also looking at pulling these individual management group definitions up to variables to simplify complete customisation. Would this be a better approach?

**Comment by erisnar** [comment] 2022-12-02 08:15
Hei @krowlandson, that would be nice! For our use case it would suffice with a variable ```mg_suffix``` as you suggest.

**Comment by krowlandson** [comment] 2022-12-06 14:36
Great, thank you for confirming @erisnar... we will discuss this and get something added to the backlog.

For now, as a workaround, are you aware that you could set `deploy_core_landing_zones = false` and then use `custom_landing_zones` to create the same hierarchy with full customisation? This would allow you to change the display names are you have requested, although is a little bit of a sledgehammer approach.

Only thing I would suggest watching out for is that the Management Group ID (the `key` for each element in `custom_landing_zones`) must match our naming convention for managed policy parameter values to work as expected.

**Comment by erisnar** [comment] 2022-12-06 14:48
@krowlandson nice. Will look into it. As the feature is nice to have we will probably wait for official release.

I experimented with your suggestion of adding a ```mg_suffix``` variable and was able to create what we wanted. Feel free to close the pull request if this does not meet the standards of this repo. Something to note is that if we add a suffix variable to display_name it might be hard to validate correct length. See Terraform issue https://github.com/hashicorp/terraform/issues/25609 and stackoverflow post https://stackoverflow.com/questions/63629916/terraform-13-validate-variable-base-on-the-value-of-another.

**Comment by krowlandson** [comment] 2022-12-29 14:57
- Linking to #115 as related.

**Comment by matt-FFFFFF** [comment] 2023-02-22 13:23
Duplicate of #115

**Closed by matt-FFFFFF** 2023-02-22 13:23 UTC
Labels: enhancement
