### ISSUE TITLE
Allow Configuration using Firewall Manager for implementing Internet Traffic and Private Traffic filtering

### ISSUE THREAD

**Issue by spotakash** [Azure/terraform-azurerm-caf-enterprise-scale#518] opened 2022-11-18 09:04 UTC
Lot of customers started using vWAN Secured HUB. They use Azure Firewall for managing all types of routing i.e. Internet and private via Azure Firewall Policies. It offers organization to operate in current model, where generally SRE operate at platform while networking is being managed by either Security or Netops (NOC).

We should have flag enable in existing module such that setting can be easily enable or disable on the fly. Default route will be updated after that.
Good guidance is written here with sample code https://github.com/nthewara/tf-secured-virtualhub

Sample code can be like for settings.connectivity.tf

``
azure_firewall = {
              enabled = false
              config = {
                address_prefix                = "10.100.0.0/24"
                enable_dns_proxy              = true
                dns_servers                   = []
                sku_tier                      = ""
                base_policy_id                = ""
                private_ip_ranges             = []
                threat_intelligence_mode      = ""
                threat_intelligence_allowlist = []
                availability_zones = {
                  zone_1 = true
                  zone_2 = true
                  zone_3 = true
                }
                internet_traffic_via_firewall = true/false
                private_traffic_via_firewall  = true/false
              }

``

**Comment by krowlandson** [comment] 2022-11-18 09:36
Thank you for raising this @spotakash 

As this is configuration which can be handled by the `azurerm_virtual_hub_route_table_route` resource type, we would usually recommend that this is managed outside of the module.

I will discuss with our team to see whether this is something we want to add to the module, but there will be a couple of constraints, specifically:

- We would need to offer this across ARM, Bicep and Terraform implementations of ALZ
- We are planning a module refactor which would be a precedence to this addition

**Comment by krowlandson** [comment] 2022-11-18 09:37
cc: @sitarant, @fguerri, @jtracey93 for discussion

**Comment by krowlandson** [comment] 2022-11-29 13:47
Closing as duplicate of #491

**Closed by krowlandson** 2022-11-29 13:47 UTC
Labels: duplicate, enhancement
