### ISSUE TITLE
Insufficient policy_definition_reference blocks

### ISSUE THREAD

**Issue by tohov** [Azure/terraform-azurerm-caf-enterprise-scale#360] opened 2022-05-03 21:32 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.1.9

**azure provider**: >= 3.0.2

**module**: 2.0.0

### Description

**Describe the bug**

Trying to deploy landing zone from scratch using the latest 2.0.0 module version, but have encountered an error which is beyond me.

When running `terraform plan` I get an error stating 

- Error: Attempt to get attribute from null value
- Error: Insufficient policy_definition_reference blocks
- Error: Error in function call

I've deployed many landing zones already but not using azurerm 3.0.0 or later in combination with module version higher than 1.1.4. I've read through the wiki article `Upgrade from v1.1.4 to v2.0.0` and resolved multiple configuration errors that were braking changes, but couldn't resolve this on my own. Assistance needed.

It seems that terraform is upset about the policy_defenition_set

**Steps to Reproduce**

1. Deploy landing zone using module 2.0.0
2. Include custom library `.\lib` with custom archetype configuration
3. No management or connectivity resources are being deployed, very minimalistic setup

**Screenshots**

![poista mut](https://user-images.githubusercontent.com/38506856/166568079-fa770018-259e-47c4-bd1f-abbdd29296cd.png)

![poistaMinut_2](https://user-images.githubusercontent.com/38506856/166568723-3d33c054-37c2-424f-b06b-de76a030d88a.png)
I did not modify the module files, this is just to illustrate what the terraform is upset about.

![poistaMinut_3](https://user-images.githubusercontent.com/38506856/166568746-dd249352-16bc-4964-bd51-49ced344cea0.png)

![poistaMinut_4](https://user-images.githubusercontent.com/38506856/166569372-3fc9a8b2-ea8d-401b-bade-21e35031d596.png)
This argument should be optional but the error is stating otherwise.

**What am I doing wrong here?**

**Additional context**

Terraform v1.1.9
Initializing Terraform configuration...
Configuring remote state backend...
Initializing plugins and modules...

------------------------------------------------------------------------
```
module.landing-zone.azurerm_management_group.level_1["/providers/Microsoft.Management/managementGroups/nnn-az"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az]
module.landing-zone.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/nnn-az-landingzones"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az-landingzones]
module.landing-zone.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/nnn-az-connectivity"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az-connectivity]
module.landing-zone.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/nnn-az-sandbox"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az-sandbox]
module.landing-zone.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/nnn-az-vdi"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az-vdi]
module.landing-zone.azurerm_management_group.level_2["/providers/Microsoft.Management/managementGroups/nnn-az-management"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az-management]
module.landing-zone.azurerm_management_group.level_3["/providers/Microsoft.Management/managementGroups/nnn-az-landingzone-prod"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az-landingzone-prod]
module.landing-zone.azurerm_management_group.level_3["/providers/Microsoft.Management/managementGroups/nnn-az-landingzone-non-prod"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az-landingzone-non-prod]
module.landing-zone.time_sleep.after_azurerm_management_group: Refreshing state... [id=2022-05-03T14:53:45Z]
module.landing-zone.time_sleep.after_azurerm_role_definition: Refreshing state... [id=2022-05-03T14:54:45Z]
module.landing-zone.azurerm_role_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/nnn-az/providers/Microsoft.Authorization/roleAssignments/339bdf8d-47fe-558c-9836-d401377482be"]: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/nnn-az/providers/Microsoft.Authorization/roleAssignments/339bdf8d-47fe-558c-9836-d401377482be]
module.landing-zone.time_sleep.after_azurerm_policy_definition: Refreshing state... [id=2022-05-03T14:54:15Z]
╷
│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/landing-zone/locals.policy_assignments.tf line 110, in locals:
│  110:       for policy_definition in policy_set_definition.template.properties.policyDefinitions :
│     ├────────────────
│     │ policy_set_definition.template is null
│ 
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Insufficient policy_definition_reference blocks
│ 
│   on .terraform/modules/landing-zone/resources.policy_set_definitions.tf line 1, in resource "azurerm_policy_set_definition" "enterprise_scale":
│    1: resource "azurerm_policy_set_definition" "enterprise_scale" {
│ 
│ At least 1 "policy_definition_reference" blocks are required.
╵
╷
│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/landing-zone/resources.policy_set_definitions.tf line 5, in resource "azurerm_policy_set_definition" "enterprise_scale":
│    5:   name         = each.value.template.name
│     ├────────────────
│     │ each.value.template is null
│ 
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/landing-zone/resources.policy_set_definitions.tf line 7, in resource "azurerm_policy_set_definition" "enterprise_scale":
│    7:   display_name = each.value.template.properties.displayName
│     ├────────────────
│     │ each.value.template is null
│ 
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/landing-zone/resources.policy_set_definitions.tf line 12, in resource "azurerm_policy_set_definition" "enterprise_scale":
│   12:       for item in each.value.template.properties.policyDefinitions :
│     ├────────────────
│     │ each.value.template is null
│ 
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Error in function call
│ 
│   on .terraform/modules/landing-zone/resources.policy_set_definitions.tf line 27, in resource "azurerm_policy_set_definition" "enterprise_scale":
│   27:   description         = try(each.value.template.properties.description, "${each.value.template.properties.displayName} Policy Set Definition at scope ${each.value.scope_id}")
│     ├────────────────
│     │ each.value.scope_id is "/providers/Microsoft.Management/managementGroups/nnn-az"
│     │ each.value.template is null
│ 
│ Call to function "try" failed: no expression succeeded:
│ - Attempt to get attribute from null value (at
│ .terraform/modules/landing-zone/resources.policy_set_definitions.tf:27,48-59)
│   This value is null, so it does not have any attributes.
│ - Attempt to get attribute from null value (at
│ .terraform/modules/landing-zone/resources.policy_set_definitions.tf:27,95-106)
│   This value is null, so it does not have any attributes.
│ 
│ At least one expression must produce a successful result.
╵

Error: Plan operation failed
```

**Comment by krowlandson** [comment] 2022-05-04 04:31
@tohov are you able to confirm whether you included any custom Policy Set Definitions in your custom `lib` folder?

**Comment by matt-FFFFFF** [comment] 2022-05-04 08:04
@tohov please can you also post your module declaration?

**Comment by tohov** [comment] 2022-05-04 08:05
@krowlandson I'm able to confirm that I only have folders `archetype_definitions`, `policy_assignments` and `policy_definitions`. So no custom policy set definitions.

**Comment by tohov** [comment] 2022-05-04 08:19
@matt-FFFFFF is this what you mean?

### main.tf
```
terraform {
  backend "remote" {
    hostname     = "companyname.scalr.io"
    organization = "env-NNNNNNNNNNNNNNN"
    workspaces {
      name = "customer-azure-landingzone"
    }
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.0.2"
      configuration_aliases = [ 
        azurerm.connectivity,
        azurerm.management,
       ]
    }
  }
}

provider "azurerm" {
  subscription_id = local.sub_management[0]
  features {}
}

provider "azurerm" {
  alias           = "management"
  subscription_id = local.sub_management[0]
  features {}
}

provider "azurerm" {
  alias           = "connectivity"
  subscription_id = local.sub_connectivity[0]
  features {}
}

data "azurerm_client_config" "core" {
  provider = azurerm
}

data "azurerm_client_config" "management" {
  provider = azurerm.management
}

data "azurerm_client_config" "connectivity" {
  provider = azurerm.connectivity
}
```

### deployLandingZone.tf
```
data "azurerm_client_config" "current" {}

module "landing-zone" {
  source  = "companyName.scalr.io/acc-NNNNNNNNNNN/landing-zone/azurerm"
  version = "2.0.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }
  root_parent_id = data.azurerm_client_config.core.tenant_id
  root_id        = var.root_id

  library_path             = "${path.root}/lib"
  default_location         = "westeurope"
  default_tags             = {}
  disable_base_module_tags = false

  # Module built-in enterprise scale landing zone structure (not used here, set both to false)
  deploy_core_landing_zones = false
  deploy_demo_landing_zones = false

  # Management
  deploy_management_resources    = false
  subscription_id_management     = data.azurerm_client_config.management.subscription_id
  configure_management_resources = local.configure_management_resources

  # Connectivity
  deploy_connectivity_resources    = false
  subscription_id_connectivity     = data.azurerm_client_config.connectivity.subscription_id
  configure_connectivity_resources = local.configure_connectivity_resources

  # Identity
  deploy_identity_resources    = false
  configure_identity_resources = local.configure_identity_resources

  # Customize landing zone deployment
  custom_landing_zones       = local.custom_landing_zones
  archetype_config_overrides = var.archetype_config_overrides
  subscription_id_overrides  = var.subscription_id_overrides 
  template_file_variables    = {
    root_id = var.root_id
  }
  ```
  
  ### locals.tf
  ```
  locals {
  sub_root         = []
  sub_management   = ["NNNNNNNN-0ba1-4f35-951d-NNNNNNNNNN"]
  sub_connectivity = ["NNNNNNNN-0f49-48dd-9a3e-NNNNNNNNNN"]
  sub_sandbox      = ["NNNNNNNN-aea6-47a6-a004-NNNNNNNNNN"]
  sub_vdi          = ["NNNNNNNN-db21-4657-aa92-NNNNNNNNNN"]
  sub_lz           = []
  sub_lz_prod      = []
  sub_lz_non_prod  = ["NNNNNNNN-70f1-4435-97aa-NNNNNNNNNN", "NNNNNNNN-553f-45bf-9b23-NNNNNNNNNN"]
}

# ARCHETYPE ASSOCIATION #
# Define the archetypes to be used with the custom management groups. Make sure the archetypes you define exists in the library path.
locals {
  arch_id_empty                = "default_empty"
  arch_id_root                 = "${var.root_id}_root"
  arch_id_management           = "${var.root_id}_management"
  arch_id_connectivity         = "${var.root_id}_connectivity"
  arch_id_sandbox              = "${var.root_id}_sandbox"
  arch_id_vdi                  = "${var.root_id}_vdi"
  arch_id_landingzone          = "${var.root_id}_landingzone"
  arch_id_landingzone_prod     = "${var.root_id}_landingzone_prod"
  arch_id_landingzone_non_prod = "${var.root_id}_landingzone_non_prod"
}

# CUSTOM MANAGEMENT GROUP HIERARCHY #
# Define your customer specific custom landing zone hierarchy here.
# If you add more management groups also add the corresponding locals to Subscription ID and Archetype association sections.
locals {
  custom_landing_zones = {
    "${var.root_id}-az" = {
      display_name               = "${var.root_id}-az-root-mg"
      parent_management_group_id = data.azurerm_client_config.core.tenant_id
      subscription_ids           = local.sub_root
      archetype_config = {
        archetype_id = local.arch_id_root
        parameters   = {}
        access_control = {
          "Reader" : [
            "1f681e5e-2f98-43e2-adb6-NNNNNNNNNN" 
          ]
        }
      }
    }
    "${var.root_id}-az-management" = {
      display_name               = "${var.root_id}-az-management-mg"
      parent_management_group_id = "${var.root_id}-az"
      subscription_ids           = local.sub_management
      archetype_config = {
        archetype_id   = local.arch_id_management
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-az-connectivity" = {
      display_name               = "${var.root_id}-az-connectivity-mg"
      parent_management_group_id = "${var.root_id}-az"
      subscription_ids           = local.sub_connectivity
      archetype_config = {
        archetype_id   = local.arch_id_connectivity
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-az-sandbox" = {
      display_name               = "${var.root_id}-az-sandbox-mg"
      parent_management_group_id = "${var.root_id}-az"
      subscription_ids           = local.sub_sandbox
      archetype_config = {
        archetype_id   = local.arch_id_empty
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-az-landingzones" = {
      display_name               = "${var.root_id}-az-landingzones-mg"
      parent_management_group_id = "${var.root_id}-az"
      subscription_ids           = local.sub_lz
      archetype_config = {
        archetype_id   = local.arch_id_landingzone
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-az-vdi" = {
      display_name               = "${var.root_id}-az-vdi-mg"
      parent_management_group_id = "${var.root_id}-az"
      subscription_ids           = local.sub_vdi
      archetype_config = {
        archetype_id   = local.arch_id_vdi
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-az-landingzone-prod" = {
      display_name               = "${var.root_id}-az-landingzone-prod-mg"
      parent_management_group_id = "${var.root_id}-az-landingzones"
      subscription_ids           = local.sub_lz_prod
      archetype_config = {
        archetype_id   = local.arch_id_landingzone_prod
        parameters     = {}
        access_control = {}
      }
    }
    "${var.root_id}-az-landingzone-non-prod" = {
      display_name               = "${var.root_id}-az-landingzone-non-prod-mg"
      parent_management_group_id = "${var.root_id}-az-landingzones"
      subscription_ids           = local.sub_lz_non_prod
      archetype_config = {
        archetype_id   = local.arch_id_landingzone_non_prod
        parameters     = {}
        access_control = {}
      }
    }
  }
}

# MANAGEMENT RESOURCE CONFIGURATION #
# Define the configuration for the management resources here
locals {
  configure_management_resources = {
    settings = {
      log_analytics = {
        enabled = false
        config = {
          retention_in_days                           = 180
          enable_monitoring_for_arc                   = false
          enable_monitoring_for_vm                    = false
          enable_monitoring_for_vmss                  = false
          enable_solution_for_agent_health_assessment = false
          enable_solution_for_anti_malware            = false
          enable_solution_for_azure_activity          = false
          enable_solution_for_change_tracking         = false
          enable_solution_for_service_map             = false
          enable_solution_for_sql_assessment          = false
          enable_solution_for_updates                 = false
          enable_solution_for_vm_insights             = false
          enable_sentinel                             = false
        }
      }
      security_center = {
        enabled = true
        config = {
          email_security_contact             = "nnn@domain.com"
          enable_defender_for_app_services   = false
          enable_defender_for_arm            = false
          enable_defender_for_containers     = false
          enable_defender_for_dns            = false
          enable_defender_for_key_vault      = false
          enable_defender_for_servers        = false
          enable_defender_for_sql_servers    = false
          enable_defender_for_sql_server_vms = false
          enable_defender_for_storage        = false
          enable_defender_for_oss_databases  = false
        }
      }
    }
    location = null
    tags     = null
    advanced = null
  }
}

# CONNECTIVITY RESOURCES CONFIGURATION #
# Define the configuration for the connectivity resources here
locals {
  configure_connectivity_resources = {
    settings = {
      hub_networks = [
        {
          enabled = false
          config = {
            address_space                = []
            location                     = null
            link_to_ddos_protection_plan = false
            dns_servers                  = []
            bgp_community                = ""
            subnets                      = []
            virtual_network_gateway = {
              enabled = false
              config = {
                address_prefix           = "10.100.1.0/24"
                gateway_sku_expressroute = "ErGw2AZ"
                gateway_sku_vpn          = "VpnGw3"
                advanced_vpn_settings = {
                  enable_bgp                       = null
                  active_active                    = null
                  private_ip_address_allocation    = ""
                  default_local_network_gateway_id = ""
                  vpn_client_configuration         = []
                  bgp_settings                     = []
                  custom_route                     = []
                }
              }
            }
            azure_firewall = {
              enabled = false
              config = {
                address_prefix                = ""
                enable_dns_proxy              = false
                dns_servers                   = []
                sku_tier                      = ""
                base_policy_id                = ""
                private_ip_ranges             = []
                threat_intelligence_mode      = ""
                threat_intelligence_allowlist = []
                availability_zones = {
                  zone_1 = false
                  zone_2 = false
                  zone_3 = false
                }
              }
            }
            spoke_virtual_network_resource_ids      = []
            enable_outbound_virtual_network_peering = false
          }
        }
      ]
      vwan_hub_networks = []
      ddos_protection_plan = {
        enabled = false
        config = {
          location = null
        }
      }
      dns = {
        enabled = false
        config = {
          location = null
          enable_private_link_by_service = {
            azure_automation_webhook             = false
            azure_automation_dscandhybridworker  = false
            azure_sql_database_sqlserver         = false
            azure_synapse_analytics_sqlserver    = false
            azure_synapse_analytics_sql          = false
            storage_account_blob                 = false
            storage_account_table                = false
            storage_account_queue                = false
            storage_account_file                 = false
            storage_account_web                  = false
            azure_data_lake_file_system_gen2     = false
            azure_cosmos_db_sql                  = false
            azure_cosmos_db_mongodb              = false
            azure_cosmos_db_cassandra            = false
            azure_cosmos_db_gremlin              = false
            azure_cosmos_db_table                = false
            azure_database_for_postgresql_server = false
            azure_database_for_mysql_server      = false
            azure_database_for_mariadb_server    = false
            azure_key_vault                      = false
            azure_kubernetes_service_management  = false
            azure_search_service                 = false
            azure_container_registry             = false
            azure_app_configuration_stores       = false
            azure_backup                         = false
            azure_site_recovery                  = false
            azure_event_hubs_namespace           = false
            azure_service_bus_namespace          = false
            azure_iot_hub                        = false
            azure_relay_namespace                = false
            azure_event_grid_topic               = false
            azure_event_grid_domain              = false
            azure_web_apps_sites                 = false
            azure_machine_learning_workspace     = false
            signalr                              = false
            azure_monitor                        = false
            cognitive_services_account           = false
            azure_file_sync                      = false
            azure_data_factory                   = false
            azure_data_factory_portal            = false
            azure_cache_for_redis                = false
          }
          private_link_locations                                 = []
          public_dns_zones                                       = []
          private_dns_zones                                      = []
          enable_private_dns_zone_virtual_network_link_on_hubs   = false
          enable_private_dns_zone_virtual_network_link_on_spokes = false
        }
      }
    }
    location = null
    tags     = null
    advanced = null
  }
}

# IDENTITY RESOURCES CONFIGURATION #
# Define the configuration for the identity resources here
locals {
  configure_identity_resources = {
    settings = {
      identity = {
        enabled = false
        config = {
          enable_deny_public_ip             = true
          enable_deny_rdp_from_internet     = true
          enable_deny_subnet_without_nsg    = true
          enable_deploy_azure_backup_on_vms = true
        }
      }
    }
  }
}
  ```
  
  ### variables.tf
  ```
variable "subscription_id_overrides" {
  description = "If specified, will move specified subscriptions under the core landing zone management group(s)"
  type        = map(list(string))
  default = {
    root           = [],
    decommissioned = [],
    sandboxes      = [],
    landing-zones  = [],
    platform       = [],
    connectivity   = [],
    management     = [],
    identity       = []
  }
}

variable "archetype_config_overrides" {
  description = "If specified, will set custom Archetype configurations to the default Enterprise-scale Management Groups"
  type        = map(any)
  default     = {}
}

variable "root_id" {
  description = "Customer specific short id of 2-4 characters used throughout the landing zone configuration"
  type        = string
}
```

**Comment by matt-FFFFFF** [comment] 2022-05-04 11:18
Thank you @tohov

I will try and reproduce today/tomorrow

**Comment by tohov** [comment] 2022-05-10 05:14
Any luck reproducing the problem?

**Comment by matt-FFFFFF** [comment] 2022-05-10 08:08
Hi @tohov, I'm afraid other commitments got in the way last week but it's on my list to do either today or tomorrow.

**Comment by matt-FFFFFF** [comment] 2022-05-12 17:23
Hi @tohov

I have begun investigating

Currently receiving plan errors for policysets that don't exist because the management group has not yet been created.

```
❯ t plan
╷
│ Error: reading Policy Set Definition "Deploy-MDFC-Config": policy.SetDefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicySetDefinitionNotFound" Message="The policy set definition 'Deploy-MDFC-Config' could not be found."
│
│   with module.enterprise_scale.data.azurerm_policy_set_definition.external_lookup["/providers/Microsoft.Management/managementGroups/alztest/providers/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config"],
│   on .terraform/modules/enterprise_scale/locals.policy_assignments.tf line 98, in data "azurerm_policy_set_definition" "external_lookup":
│   98: data "azurerm_policy_set_definition" "external_lookup" {
│
╵
╷
│ Error: reading Policy Set Definition "Deploy-Diagnostics-LogAnalytics": policy.SetDefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicySetDefinitionNotFound" Message="The policy set definition 'Deploy-Diagnostics-LogAnalytics' could not be found."
│
│   with module.enterprise_scale.data.azurerm_policy_set_definition.external_lookup["/providers/Microsoft.Management/managementGroups/alztest/providers/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics"],
│   on .terraform/modules/enterprise_scale/locals.policy_assignments.tf line 98, in data "azurerm_policy_set_definition" "external_lookup":
│   98: data "azurerm_policy_set_definition" "external_lookup" {
│
╵
```

**Comment by matt-FFFFFF** [comment] 2022-05-12 17:52
Hi @tohov 

I have found an issue, which is currently hampering my progress

* #373 

Do you have any custom policy/policy set definitions assigned in your archetype configs?

**Comment by matt-FFFFFF** [comment] 2022-05-12 18:23
Scratch that - I have deployed using a copy of the module's built-in archetypes, renamed and references changed to the new custom root management group.

Apply worked.

To totally reproduce I'll need a representation of your /lib folder.

**Comment by tohov** [comment] 2022-05-12 20:53
I will work on this tomorrow 💪🏼

**Comment by tohov** [comment] 2022-05-17 06:34
@matt-FFFFFF Your GitHub profile has link to someone else's LinkedIn profile other than yours. :) 

Hopefully this archive has all the files you need to reproduce the problem
[Issue_360.zip](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/files/8705784/Issue_360.zip)

**Comment by matt-FFFFFF** [comment] 2022-05-17 07:37
@tohov - thanks! this is fixed now

**Comment by matt-FFFFFF** [comment] 2022-05-17 07:37
@krowlandson is going to try and repro this today

**Comment by krowlandson** [comment] 2022-05-17 10:11
Morning @tohov!

So first problem is that you're referencing an old version of the `Deploy-ASCDF-Config` Policy Set Definition, which needs to be updated to `Deploy-MDFC-Config` in your `archetype_definition_root.json` custom Archetype Definition file.

However, this then results in a number of other errors relating to missing Policy Definitions when trying to calculate the required Role Assignments for Policies, such as the following:

```shell
╷
│ Error: reading Policy Definition "Deploy-Diagnostics-NetworkSecurityGroups": policy.DefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicyDefinitionNotFound" Message="The policy definition 'Deploy-Diagnostics-NetworkSecurityGroups' could not be found."
│ 
│   with module.landing-zone.data.azurerm_policy_definition.external_lookup["/providers/Microsoft.Management/managementGroups/360/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-NetworkSecurityGroups"],
│   on .terraform/modules/landing-zone/locals.policy_assignments.tf line 160, in data "azurerm_policy_definition" "external_lookup":
│  160: data "azurerm_policy_definition" "external_lookup" {
│ 
╵
```

These subsequent errors appears to be due to your `root` Management Group having the `-az` suffix (`${var.root_id}-az`) which means the expected scope for these Policies doesn't actually exist.

To explain this a bit better, in my demo using your code (with a few necessary environmental updates), I use a value of `360` for the `var-root_id`. This means your code will create a `root` Management Group with the ID `360-az`. In the error above, you can see that the module is expecting the Policy Definitions to exist at the scope of `360` (which doesn't exist). Setting `deploy_core_landing_zones = true` appears to initially fix these problems as that Management Group scope (and associated Policies) now exist in the plan, but of course you don't want these, and things will be missing at your custom scopes.

You could fix this multiple ways, but I think a good solution to this problem appears to be using the following code to add the `-az` suffix to `var.root_id` and then referencing `local.root_id` throughout your code instead of `var.root_id` or `${var.root_id}-az`:

```hcl
locals {
  root_id = "${var.root_id}-az"
}
```

> Don't forget to update the value for `root_id` in the module declaration, in addition to within the `locals.tf` file

I've not run `terraform apply`, but this at least results in a successful plan.

![image](https://user-images.githubusercontent.com/12268562/168782901-a5537c31-82e9-4a26-9fe7-3ce9b868ef0b.png)

As a side point, you can also remove the `template_file_variables` input variable if you replace `${root_id}` in your Archetype Definition templates with `${root_scope_id}` which represents the same value. I guess it would make sense to also include `root_id` as a standard value though as this probably makes more sense, so will add this to the backlog.

**Comment by tohov** [comment] 2022-05-19 20:31
@krowlandson This resolved my issues. Thank you very much for your help and comments on how to set the root_id.

**Comment by krowlandson** [comment] 2022-05-26 06:58
Closing as resolved. Thank you for confirming @tohov

**Closed by krowlandson** 2022-05-26 06:58 UTC
Labels: Needs: Attention :wave:
